// data.js

export const chainsData = [
  {
    name: 'Ethereum',
    symbol: 'ETH',
    price: 4000.23,
    icon: '🔷',
    marketCap: 367.73, // in Billions
    rank: 2,
    volume24h: 18.77, // in Billions
    supply: 120.27, // in Millions
    info: {
      website: 'https://ethereum.org/en/',
      whitepaper: 'https://ethereum.org/en/whitepaper/',
      blockExplorers: ['https://etherscan.io/'],
      github: 'https://github.com/ethereum',
    },
    about: `Ethereum is a global, decentralized platform for money and new kinds of applications. On Ethereum, you can write code that controls digital value, runs exactly as programmed, and is accessible anywhere in the world. It is the second-largest cryptocurrency by market capitalization after Bitcoin. Ethereum is not just a cryptocurrency; it's a technology that lets you send cryptocurrency to anyone for a small fee, and power decentralized applications (dApps) that everyone can use and no one can take down.

    The Ethereum network is constantly evolving, with ongoing upgrades aimed at improving its scalability, security, and sustainability. The most significant of these was "The Merge," which transitioned Ethereum from a Proof-of-Work (PoW) to a Proof-of-Stake (PoS) consensus mechanism, drastically reducing its energy consumption.`,
    founders: [
      { id: 1, name: 'Vitalik Buterin', role: 'Creator', bio: 'A Russian-Canadian programmer and writer who is primarily known as one of the co-founders of Ethereum.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=VB', socialLinks: { twitter: 'https://twitter.com/VitalikButerin', github: 'https://github.com/vbuterin', website: 'https://vitalik.ca/' } },
      { id: 2, name: 'Gavin Wood', role: 'Co-founder', bio: 'A British computer scientist who is a co-founder of Ethereum and creator of Polkadot and Kusama.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=GW', socialLinks: { twitter: 'https://twitter.com/gavofyork', github: 'https://github.com/gavofyork', website: 'https://gavwood.com/' } },
      { id: 3, name: 'Charles Hoskinson', role: 'Co-founder', bio: 'An American entrepreneur who is a co-founder of Ethereum and founder of Cardano.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=CH', socialLinks: { twitter: 'https://twitter.com/IOHK_Charles', github: 'https://github.com/input-output-hk', website: 'https://iohk.io/' } },
      { id: 4, name: 'Anthony Di Iorio', role: 'Co-founder', bio: 'A Canadian entrepreneur and venture capitalist who is a co-founder of Ethereum.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=AD', socialLinks: { twitter: 'https://twitter.com/diiorioanthony', website: 'https://anthony.diiorio.ca/' } },
    ],
    news: [
      { id: 1, title: 'Grayscale Files Confidential Application for IPO With New Ethereum Trust', content: 'Details about Grayscale\'s IPO application for a new Ethereum Trust. This is a longer content to demonstrate scrolling within the detail page. Grayscale Investments, the world\'s largest digital asset manager, has confidentially filed an application with the SEC to convert its Ethereum Trust into an Exchange Traded Fund (ETF). This move signals growing institutional interest in Ethereum and could pave the way for more mainstream adoption of the cryptocurrency. The filing is a significant step, following similar efforts for Bitcoin ETFs, and highlights the increasing maturity of the digital asset market.', tags: ['Market', 'Investment', 'Ethereum'], imageUrl:"https://images.unsplash.com/photo-1660030584437-10c529d4a6cb?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZXRoZXJldW0lMjBuZXdzfGVufDB8fDB8fHww" },
      { id: 2, title: 'Ethereum Price Surges Amidst Market Optimism', content: 'Analysis of the recent price surge and market sentiment. The price of Ethereum (ETH) has seen a significant surge over the past week, driven by renewed market optimism and positive developments within the ecosystem. Analysts point to increasing DeFi activity and anticipation around upcoming network upgrades as key factors. Investors are closely watching the market for further signs of a bull run, with many predicting ETH to reach new all-time highs in the near future. The overall sentiment in the crypto market remains bullish, supporting Ethereum\'s upward trajectory.', tags: ['Market', 'Price', 'Ethereum'], imageUrl:"https://images.unsplash.com/photo-1660030584437-10c529d4a6cb?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZXRoZXJldW0lMjBuZXdzfGVufDB8fDB8fHww" },
      { id: 3, title: 'Vitalik Buterin Discusses Ethereum\'s Future Roadmap', content: 'Key takeaways from Vitalik\'s latest presentation on Ethereum\'s development. Vitalik Buterin, co-founder of Ethereum, recently shared insights into the network\'s long-term roadmap during a virtual conference. He emphasized continued focus on scalability, security, and decentralization, outlining plans for further sharding implementation and improvements to the Proof-of-Stake mechanism. Buterin also touched upon the importance of layer-2 solutions in enhancing user experience and reducing transaction costs. His vision reinforces Ethereum\'s commitment to becoming a global, scalable, and sustainable blockchain platform.', tags: ['Technology', 'Development', 'Ethereum'], imageUrl: "https://images.unsplash.com/photo-1660030584437-10c529d4a6cb?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZXRoZXJldW0lMjBuZXdzfGVufDB8fDB8fHww", },
      { id: 4, title: 'New DeFi Protocol Launches on Ethereum Network', content: 'Overview of a new decentralized finance application. A groundbreaking new DeFi protocol, "YieldNexus," has officially launched on the Ethereum network, promising innovative yield farming opportunities. The protocol aims to optimize liquidity provision and enhance returns for users through advanced algorithmic strategies. Early adopters are reporting promising results, and the project has quickly gained traction within the DeFi community. This launch further solidifies Ethereum\'s position as the leading platform for decentralized finance innovation.', tags: ['DeFi', 'Technology'], imageUrl: "https://images.unsplash.com/photo-1660030584437-10c529d4a6cb?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZXRoZXJldW0lMjBuZXdzfGVufDB8fDB8fHww", },
      { id: 5, title: 'Ethereum Gas Fees See Significant Drop', content: 'Report on the recent reduction in transaction costs. Ethereum gas fees have experienced a notable decline recently, providing much-needed relief to users and developers. This reduction is attributed to a combination of factors, including network optimization, increased adoption of layer-2 scaling solutions, and a temporary decrease in network congestion. Lower gas fees make transactions more affordable and accessible, fostering greater participation in the Ethereum ecosystem and encouraging the development of new dApps.', tags: ['Technology', 'Fees'], imageUrl: "https://media.istockphoto.com/id/909000600/photo/golden-coins-on-circuit-board-3d-rendering.webp?a=1&b=1&s=612x612&w=0&k=20&c=dR7TtIuXDxvWB-1EXzcRdwyswFzhiZeoXfohTVy8Q-w=", },
      { id: 6, title: 'Major Upgrade to Ethereum\'s Scaling Solutions Announced', content: 'Details on the latest advancements in layer-2 technologies.', tags: ['Technology', 'Scaling'], imageUrl: "https://media.istockphoto.com/id/948542404/photo/3d-rendering-of-human-brain-on-technology-background.webp?a=1&b=1&s=612x612&w=0&k=20&c=KTkIOtKDeZSDmHV5XUZgcoICO7k4vTlQ7-brDxuNSbk=", },
      { id: 7, title: 'Ethereum NFT Market Reaches All-Time Highs', content: 'Insights into the booming non-fungible token ecosystem.', tags: ['NFT', 'Market'], imageUrl: "https://media.istockphoto.com/id/123456789/photo/nft-art-collection.webp?a=1&b=1&s=612x612&w=0&k=20&c=ABC123", },
      { id: 8, title: 'Enterprise Ethereum Alliance Welcomes New Members', content: 'List of new companies joining the EEA and their contributions.', tags: ['Enterprise', 'Partnership'], imageUrl: "https://media.istockphoto.com/id/123456789/photo/nft-art-collection.webp?a=1&b=1&s=612x612&w=0&k=20&c=ABC123", },
    ],
    faqs: [
      { id: 1, question: 'What is Ethereum?', answer: 'Ethereum is a decentralized, open-source blockchain with smart contract functionality. Ether (ETH) is the native cryptocurrency of the Ethereum platform. It is the most actively used blockchain.', },
      { id: 2, question: 'Who runs Ethereum?', answer: 'Ethereum is maintained by a global network of decentralized nodes, meaning no single entity "runs" it. It\'s a community-driven project with contributions from developers worldwide.', },
      { id: 3, question: 'What are smart contracts?', answer: 'Smart contracts are self-executing contracts with the terms of the agreement directly written into code. They run on the blockchain and automatically execute when conditions are met.', },
      { id: 4, question: 'What about Ethereum\'s energy consumption?', answer: 'Ethereum transitioned from Proof-of-Work (PoW) to Proof-of-Stake (PoS) with "The Merge," significantly reducing its energy consumption by over 99%.', },
      { id: 5, question: 'What is the difference between Ethereum and Bitcoin?', answer: 'Bitcoin is primarily a digital currency for transactions, while Ethereum is a platform for building decentralized applications (dApps) and smart contracts, with Ether as its native token.', },
      { id: 6, question: 'What is Web3?', answer: 'Web3 refers to the next generation of the internet, built on decentralized blockchain technologies, enabling peer-to-peer interactions without intermediaries.', },
      { id: 7, question: 'Why is Web3 important?', answer: 'Web3 aims to give users more control over their data and digital identities, fostering a more open, transparent, and decentralized internet.', },
      { id: 8, question: 'What is ether (ETH)?', answer: 'Ether (ETH) is the native cryptocurrency of the Ethereum blockchain. It is used to pay for transaction fees (gas) and as a store of value.', },
      { id: 9, question: 'What is an Ethereum wallet?', answer: 'An Ethereum wallet is a digital tool that allows you to store, send, and receive Ether (ETH) and other tokens on the Ethereum blockchain. It manages your public and private keys.', },
      { id: 10, question: 'How to stay safe?', answer: 'To stay safe, always use strong, unique passwords, enable two-factor authentication (2FA), be wary of phishing scams, and use reputable wallets and exchanges. Never share your private keys or seed phrase.', },
      { id: 11, question: 'Ethereum security and scam prevention', answer: 'Ethereum security involves understanding common scams like phishing, fake giveaways, and malicious smart contracts. Always verify URLs, use hardware wallets for significant funds, and educate yourself on best practices.', },
      { id: 12, question: 'What are gas fees?', answer: 'Gas fees are the transaction costs on the Ethereum network, paid in Ether (ETH). They compensate miners/validators for processing and validating transactions and smart contract executions.', },
      { id: 13, question: 'How do I pay less gas?', answer: 'To pay less gas, transact during off-peak hours when network congestion is lower, use layer-2 scaling solutions (like Arbitrum or Optimism), or utilize gas fee trackers to find optimal times.', },
      { id: 14, question: 'What causes high gas?', answer: 'High gas fees are primarily caused by network congestion. When many users are trying to make transactions simultaneously, the demand for block space increases, driving up gas prices.', },
      { id: 15, question: 'Why do we need gas?', answer: 'Gas is essential to prevent spam on the network and to compensate validators for the computational resources required to process transactions and execute smart contracts, ensuring network security and stability.', },
      { id: 16, question: 'How is gas calculated?', answer: 'Gas is calculated based on the complexity of the transaction. Each operation on the Ethereum Virtual Machine (EVM) has a gas cost. The total gas used is multiplied by the gas price (Gwei) to get the total fee.', },
    ],
    relatedChains: [ // These are references to other chains in the 'chainsData' array by name
      { name: 'Polygon', change: 0.02 },
      { name: 'Arbitrum', change: -0.01 },
      { name: 'Optimism', change: 0.05 },
      { name: 'BNB Chain', change: -0.02 },
      { name: 'Solana', change: 0.03 },
      { name: 'Cardano', change: -0.005 },
      { name: 'Polkadot', change: 0.00 },
      { name: 'Avalanche', change: 0.01 },
      { name: 'XRP', change: -0.002 },
      { name: 'Litecoin', change: 0.005 },
      { name: 'Chainlink', change: 0.01 },
      { name: 'Cosmos', change: -0.003 },
      { name: 'Near Protocol', change: 0.02 },
      { name: 'Tron', change: 0.001 },
      { name: 'VeChain', change: 0.0005 },
      { name: 'Monero', change: -0.008 },
    ],
    backgroundImages: [
      "https://images.unsplash.com/photo-1645516484419-35a747c99474?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8ZXRoZXJldW18ZW58MHx8MHx8fDA%3D",
    ],
  },
  {
    name: 'BNB Chain',
    symbol: 'BNB',
    price: 600.50,
    icon: '🦊',
    marketCap: 90.00, // in Billions
    rank: 4,
    volume24h: 5.50, // in Billions
    supply: 150.00, // in Millions
    info: {
      website: 'https://www.binance.com/',
      whitepaper: 'https://www.binance.com/en/whitepaper',
      blockExplorers: ['https://bscscan.com/'],
      github: 'https://github.com/binance-chain',
    },
    about: `Binance is the world's leading blockchain ecosystem and cryptocurrency infrastructure provider with a financial product suite that includes the largest digital asset exchange by volume. It was founded in 2017 by Changpeng Zhao (CZ) and Yi He. Binance offers a wide range of services beyond just crypto trading, including a blockchain network (BNB Chain), a venture capital arm (Binance Labs), an academy, research, and a charity foundation.

    The company aims to increase the freedom of money globally and is committed to providing a secure, fast, and reliable platform for digital asset transactions. Its ecosystem is constantly expanding, supporting various blockchain initiatives and fostering innovation in the decentralized space.`,
    founders: [
      { id: 1, name: 'Changpeng Zhao (CZ)', role: 'Founder & CEO', bio: 'A Chinese-Canadian business executive, widely known as the founder and CEO of Binance, the world\'s largest cryptocurrency exchange by trading volume.', imageUrl: 'https://placehold.co/80x80/F3BA2F/FFFFFF?text=CZ', socialLinks: { twitter: 'https://twitter.com/cz_binance', website: 'https://www.binance.com/en/blog/from-cz' } },
      { id: 2, name: 'Yi He', role: 'Co-founder & CMO', bio: 'A co-founder of Binance and its Chief Marketing Officer. She is instrumental in Binance\'s brand building and global expansion.', imageUrl: 'https://placehold.co/80x80/F3BA2F/FFFFFF?text=YH', socialLinks: { twitter: 'https://twitter.com/heyibinance' } },
    ],
    news: [
      { id: 1, title: 'Binance Launches New Innovation Zone for High-Potential Projects', content: 'Details about Binance\'s new platform for emerging cryptocurrencies and blockchain projects. This zone aims to list tokens with higher volatility and risk, but also higher potential for growth. Binance encourages users to conduct thorough research before trading in this zone.', tags: ['Exchange', 'Innovation', 'New Listing'], imageUrl:"https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" },
      { id: 2, title: 'BNB Price Reacts to Latest Burning Event', content: 'Analysis of the recent BNB burn and its impact on the token\'s supply and price. Binance regularly conducts BNB burns to reduce its total supply, aiming to increase its value over time. The latest burn removed a significant amount of BNB from circulation, leading to a noticeable price movement.', tags: ['Market', 'BNB', 'Burning'], imageUrl:"https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" },
      { id: 3, title: 'Binance Smart Chain (BSC) Sees Record dApp Activity', content: 'Report on the surge in decentralized application usage and transaction volume on BSC. The low transaction fees and high throughput of Binance Smart Chain continue to attract developers and users, leading to a booming ecosystem of dApps, including DeFi protocols and NFT marketplaces.', tags: ['BSC', 'dApps', 'Technology'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D", },
      { id: 4, title: 'Binance Labs Invests in Promising Blockchain Startups', content: 'Overview of recent investments made by Binance\'s venture capital arm into emerging blockchain companies. Binance Labs actively supports innovative projects across various sectors of the blockchain industry, contributing to the growth and adoption of decentralized technologies.', tags: ['Investment', 'Binance Labs', 'Startup'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D", },
      { id: 5, title: 'Binance Academy Releases New Educational Content', content: 'Announcement of new courses and articles on blockchain and cryptocurrency for users. Binance Academy is a free educational platform that provides comprehensive knowledge about crypto, blockchain, and related topics, aiming to increase financial literacy in the space.', tags: ['Education', 'Community'], imageUrl: "https://media.istockphoto.com/id/1325179929/photo/online-education-platforms-concept-e-learning-webinar-internet-technology.webp?b=1&s=170667a&w=0&k=20&c=054592078921", },
      { id: 6, title: 'CZ Addresses Community Concerns on Exchange Stability', content: 'Changpeng Zhao, CEO of Binance, provides updates on the exchange\'s operational stability and security measures. Transparency and user trust are key priorities for Binance, and CZ frequently communicates with the community to address any concerns.', tags: ['Leadership', 'Exchange'], imageUrl: "https://media.istockphoto.com/id/1325179929/photo/online-education-platforms-concept-e-learning-webinar-internet-technology.webp?b=1&s=170667a&w=0&k=20&c=054592078921", },
      { id: 7, title: 'Binance Charity Donates to Global Disaster Relief Efforts', content: 'News on Binance Charity\'s latest contributions to humanitarian causes worldwide. Binance Charity leverages blockchain technology for transparent and efficient fundraising and distribution of aid, demonstrating the social impact of crypto.', tags: ['Charity', 'Social Impact'], imageUrl: "https://media.istockphoto.com/id/1325179929/photo/online-education-platforms-concept-e-learning-webinar-internet-technology.webp?b=1&s=170667a&w=0&k=20&c=054592078921", },
      { id: 8, title: 'New Fiat On-Ramps Added to Binance Platform', content: 'Binance expands its fiat currency support, allowing more users to easily convert traditional money to crypto. This move aims to improve accessibility and onboarding for new users globally.', tags: ['Fiat', 'Onboarding'], imageUrl: "https://media.istockphoto.com/id/1325179929/photo/online-education-platforms-concept-e-learning-webinar-internet-technology.webp?b=1&s=170667a&w=0&k=20&c=054592078921", },
    ],
    faqs: [
      { id: 1, question: 'What is Binance?', answer: 'Binance is the world\'s largest cryptocurrency exchange by trading volume, offering a platform for trading various cryptocurrencies.', },
      { id: 2, question: 'What is BNB?', answer: 'BNB is the native cryptocurrency of the Binance ecosystem. It powers the BNB Chain and is used for trading fees, staking, and participation in token sales on Binance Launchpad.', },
      { id: 3, question: 'How does Binance Smart Chain (BSC) work?', answer: 'Binance Smart Chain (BSC) is a blockchain network built for running smart contract-based applications. It operates in parallel with Binance Chain and offers high transaction speeds and low fees.', },
      { id: 4, question: 'Who founded Binance?', answer: 'Binance was founded by Changpeng Zhao (CZ) in 2017.', },
      { id: 5, question: 'Is Binance regulated?', answer: 'Binance operates globally and adheres to regulatory requirements in various jurisdictions. Its regulatory status varies by region.', },
      { id: 6, question: 'What is Binance Launchpad?', answer: 'Binance Launchpad is a platform for launching new blockchain projects, allowing users to participate in token sales (IEOs) for promising new cryptocurrencies.', },
      { id: 7, question: 'What are BNB burns?', answer: 'BNB burns are a mechanism where a portion of BNB tokens are permanently removed from circulation, reducing the total supply and aiming to increase the token\'s value.', },
      { id: 8, question: 'How do I secure my Binance account?', answer: 'To secure your Binance account, enable Two-Factor Authentication (2FA), use a strong, unique password, enable Anti-Phishing Code, and be wary of suspicious emails or links.', },
    ],
    relatedChains: [
      { name: 'Ethereum', change: 0.01 },
      { name: 'Solana', change: 0.03 },
      { name: 'Cardano', change: -0.005 },
      { name: 'Polkadot', change: 0.00 },
      { name: 'Avalanche', change: 0.01 },
      { name: 'XRP', change: -0.002 },
      { name: 'Polygon', change: 0.02 },
      { name: 'Arbitrum', change: -0.01 },
      { name: 'Optimism', change: 0.05 },
      { name: 'Litecoin', change: 0.005 },
      { name: 'Chainlink', change: 0.01 },
      { name: 'Cosmos', change: -0.003 },
      { name: 'Near Protocol', change: 0.02 },
      { name: 'Tron', change: 0.001 },
      { name: 'VeChain', change: 0.0005 },
      { name: 'Monero', change: -0.008 },
    ],
    backgroundImages: [
      "https://images.unsplash.com/photo-1625207897487-af5f478c1d7c?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YmluYW5jZXxlbnwwfHwwfHx8MA%3D%3D",
    ],
  },
  // Add 18 more placeholder chains here to reach 20 total
  {
    name: 'Solana',
    symbol: 'SOL',
    price: 150.00,
    icon: '🌊',
    marketCap: 65.00,
    rank: 5,
    volume24h: 3.00,
    supply: 450.00,
    info: { website: 'https://solana.com/', whitepaper: '#', blockExplorers: ['https://solscan.io/'], github: 'https://github.com/solana-labs' },
    about: 'Solana is a high-performance blockchain platform that supports decentralized applications and crypto projects.',
    founders: [{ id: 1, name: 'Anatoly Yakovenko', role: 'Founder', bio: 'Creator of Solana.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=AY', socialLinks: { twitter: 'https://twitter.com/aeyakovenko' } }],
    news: [{ id: 1, title: 'Solana Ecosystem Growth', content: 'Solana continues to grow rapidly.', tags: ['Ecosystem'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Solana?', answer: 'Solana is a fast, secure, and censorship-resistant blockchain providing the open infrastructure required for global adoption.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }, { name: 'BNB Chain', change: -0.02 }],
    backgroundImages: ["https://images.unsplash.com/photo-1660062993798-0c28ee1a1d9b?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8c29sYW5hfGVufDB8fDB8fHww"],
  },
  {
    name: 'Cardano',
    symbol: 'ADA',
    price: 0.45,
    icon: '🔵',
    marketCap: 16.00,
    rank: 10,
    volume24h: 0.50,
    supply: 35.00,
    info: { website: 'https://cardano.org/', whitepaper: '#', blockExplorers: ['https://cardanoscan.io/'], github: 'https://github.com/input-output-hk' },
    about: 'Cardano is a proof-of-stake blockchain platform that aims to allow "changemakers, innovators and visionaries" to bring about positive global change.',
    founders: [{ id: 1, name: 'Charles Hoskinson', role: 'Founder', bio: 'Co-founder of Ethereum and founder of Cardano.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=CH', socialLinks: { twitter: 'https://twitter.com/IOHK_Charles' } }],
    news: [{ id: 1, title: 'Cardano Smart Contracts', content: 'Alonzo hard fork brings smart contracts to Cardano.', tags: ['Smart Contracts'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Cardano?', answer: 'Cardano is a decentralized public blockchain and cryptocurrency project.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }, { name: 'Polkadot', change: 0.00 }],
    backgroundImages: ["https://images.unsplash.com/photo-1631897641257-584352a977a1?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Q2FyZGFub3xlbnwwfHwwfHx8MA%3D%3D"],
  },
  {
    name: 'Polkadot',
    symbol: 'DOT',
    price: 7.00,
    icon: '🔴',
    marketCap: 9.00,
    rank: 15,
    volume24h: 0.30,
    supply: 1.20,
    info: { website: 'https://polkadot.network/', whitepaper: '#', blockExplorers: ['https://polkascan.io/'], github: 'https://github.com/paritytech/polkadot' },
    about: 'Polkadot is a multi-chain framework that allows different blockchains to interoperate.',
    founders: [{ id: 1, name: 'Gavin Wood', role: 'Co-founder', bio: 'Co-founder of Ethereum and creator of Polkadot.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=GW', socialLinks: { twitter: 'https://twitter.com/gavofyork' } }],
    news: [{ id: 1, title: 'Polkadot Parachain Auctions', content: 'Polkadot\'s parachain auctions are driving ecosystem growth.', tags: ['Parachains'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Polkadot?', answer: 'Polkadot is a sharded protocol that enables blockchain networks to operate together seamlessly.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }, { name: 'Cardano', change: -0.005 }],
    backgroundImages: ["https://images.unsplash.com/photo-1643616802160-bcca2171c24a?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8UG9sa2Fkb3R8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Avalanche',
    symbol: 'AVAX',
    price: 30.00,
    icon: '❄️',
    marketCap: 12.00,
    rank: 10,
    volume24h: 0.80,
    supply: 390.00,
    info: { website: 'https://www.avax.network/', whitepaper: '#', blockExplorers: ['https://avascan.info/'], github: 'https://github.com/ava-labs' },
    about: 'Avalanche is an open, programmable smart contracts platform for decentralized applications.',
    founders: [{ id: 1, name: 'Emin Gün Sirer', role: 'CEO', bio: 'Founder of Ava Labs, the team behind Avalanche.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=EGS', socialLinks: { twitter: 'https://twitter.com/el33th4xor' } }],
    news: [{ id: 1, title: 'Avalanche Subnets', content: 'Subnets are driving new use cases on Avalanche.', tags: ['Subnets'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Avalanche?', answer: 'Avalanche is a platform for launching decentralized applications and enterprise blockchain deployments in one interoperable, highly scalable ecosystem.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }, { name: 'BNB Chain', change: -0.02 }],
    backgroundImages: ["https://images.unsplash.com/photo-1493851074046-730f5fbdbebb?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDJ8fEF2YWxhbmNoZXxlbnwwfHwwfHx8MA%3D%3D"],
  },
  {
    name: 'XRP',
    symbol: 'XRP',
    price: 0.50,
    icon: '💧',
    marketCap: 25.00,
    rank: 6,
    volume24h: 1.50,
    supply: 50.00,
    info: { website: 'https://ripple.com/xrp/', whitepaper: '#', blockExplorers: ['https://bithomp.com/'], github: 'https://github.com/ripple' },
    about: 'XRP is a digital asset built for payments. It is the native digital asset on the XRP Ledger—an open-source, permissionless, and decentralized blockchain technology.',
    founders: [{ id: 1, name: 'Chris Larsen', role: 'Co-founder', bio: 'Co-founder of Ripple and OpenCoin.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=CL', socialLinks: { twitter: 'https://twitter.com/chrislarsensf' } }],
    news: [{ id: 1, title: 'XRP Ledger Updates', content: 'New features and improvements coming to the XRP Ledger.', tags: ['Ledger'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is XRP?', answer: 'XRP is a digital asset native to the XRP Ledger, an open-source, permissionless, and decentralized blockchain technology that can settle transactions in 3-5 seconds.' }],
    relatedChains: [{ name: 'BNB Chain', change: -0.02 }],
    backgroundImages: ["https://images.unsplash.com/photo-1628238289092-b94f5c5b9375?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8eHJwfGVufDB8fDB8fHww"],
  },
  {
    name: 'Litecoin',
    symbol: 'LTC',
    price: 75.00,
    icon: '💰'  ,
    marketCap: 5.50,
    rank: 20,
    volume24h: 0.40,
    supply: 74.00,
    info: { website: 'https://litecoin.org/', whitepaper: '#', blockExplorers: ['https://live.blockcypher.com/ltc/'], github: 'https://github.com/litecoin-project/litecoin' },
    about: 'Litecoin is a peer-to-peer cryptocurrency and open-source software project released under the MIT/X11 license.',
    founders: [{ id: 1, name: 'Charlie Lee', role: 'Creator', bio: 'A former Google engineer who created Litecoin.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=CL', socialLinks: { twitter: 'https://twitter.com/SatoshiLite' } }],
    news: [{ id: 1, title: 'Litecoin Halving Event', content: 'Anticipation builds for the next Litecoin halving.', tags: ['Halving'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Litecoin?', answer: 'Litecoin is a cryptocurrency that enables instant, near-zero cost payments to anyone in the world.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1580901165665-40e4e2513912?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bGl0Y29pbnxlbnwwfHwwfHx8MA%3D%3D"],
  },
  {
    name: 'Chainlink',
    symbol: 'LINK',
    price: 15.00,
    icon: '🔗',
    marketCap: 8.00,
    rank: 25,
    volume24h: 0.60,
    supply: 550.00,
    info: { website: 'https://chain.link/', whitepaper: '#', blockExplorers: ['https://etherscan.io/token/0x514910771af9ca653ac5e856346a21da8b9158ed'], github: 'https://github.com/smartcontractkit' },
    about: 'Chainlink is a decentralized oracle network that provides real-world data to smart contracts on the blockchain.',
    founders: [{ id: 1, name: 'Sergey Nazarov', role: 'Co-founder', bio: 'Co-founder of Chainlink.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=SN', socialLinks: { twitter: 'https://twitter.com/SergeyNazarov' } }],
    news: [{ id: 1, title: 'Chainlink Integrations', content: 'Chainlink expands integrations across various blockchains.', tags: ['Oracles'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Chainlink?', answer: 'Chainlink is a decentralized oracle network that aims to connect smart contracts with real-world data, events, and payments.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Cosmos',
    symbol: 'ATOM',
    price: 10.00,
    icon: '🌌',
    marketCap: 4.00,
    rank: 35,
    volume24h: 0.25,
    supply: 390.00,
    info: { website: 'https://cosmos.network/', whitepaper: '#', blockExplorers: ['https://www.mintscan.io/cosmos'], github: 'https://github.com/cosmos' },
    about: 'Cosmos is an ecosystem of connected blockchains built for scalability and interoperability.',
    founders: [{ id: 1, name: 'Jae Kwon', role: 'Co-founder', bio: 'Co-founder of Cosmos and Tendermint.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=JK', socialLinks: { twitter: 'https://twitter.com/jaekwon' } }],
    news: [{ id: 1, title: 'Cosmos Interoperability', content: 'Cosmos Hub enhances cross-chain communication.', tags: ['Interoperability'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Cosmos?', answer: 'Cosmos is a decentralized network of independent parallel blockchains, each powered by BFT consensus algorithms like Tendermint consensus.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Near Protocol',
    symbol: 'NEAR',
    price: 6.00,
    icon: '🌟',
    marketCap: 2.50,
    rank: 40,
    volume24h: 0.15,
    supply: 1.00,
    info: { website: 'https://near.org/', whitepaper: '#', blockExplorers: ['https://explorer.near.org/'], github: 'https://github.com/near' },
    about: 'NEAR Protocol is a sharded, proof-of-stake blockchain designed for usability and scalability.',
    founders: [{ id: 1, name: 'Illia Polosukhin', role: 'Co-founder', bio: 'Co-founder of NEAR Protocol.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=IP', socialLinks: { twitter: 'https://twitter.com/ilblackdragon' } }],
    news: [{ id: 1, title: 'NEAR Ecosystem Grants', content: 'NEAR Foundation announces new grants for developers.', tags: ['Grants'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is NEAR Protocol?', answer: 'NEAR Protocol is a layer-one blockchain that is designed to be a community-run cloud computing platform and eliminates some of the limitations that have plagued competing blockchains.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Tron',
    symbol: 'TRX',
    price: 0.10,
    icon: '🚀',
    marketCap: 9.00,
    rank: 18,
    volume24h: 0.50,
    supply: 88.00,
    info: { website: 'https://tron.network/', whitepaper: '#', blockExplorers: ['https://tronscan.org/'], github: 'https://github.com/tronprotocol' },
    about: 'TRON is a decentralized blockchain-based operating system with high throughput, high scalability, and high availability.',
    founders: [{ id: 1, name: 'Justin Sun', role: 'Founder', bio: 'Founder of TRON and CEO of BitTorrent.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=JS', socialLinks: { twitter: 'https://twitter.com/justinsuntron' } }],
    news: [{ id: 1, title: 'TRON DeFi Expansion', content: 'TRON\'s DeFi ecosystem sees significant growth.', tags: ['DeFi'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is TRON?', answer: 'TRON is a blockchain-based operating system that aims to decentralize the web.' }],
    relatedChains: [{ name: 'BNB Chain', change: -0.02 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'VeChain',
    symbol: 'VET',
    price: 0.03,
    icon: '🦊',
    marketCap: 2.00,
    rank: 55,
    volume24h: 0.10,
    supply: 72.00,
    info: { website: 'https://www.vechain.com/', whitepaper: '#', blockExplorers: ['https://explore.vechain.org/'], github: 'https://github.com/vechain' },
    about: 'VeChain is a blockchain platform designed to enhance supply chain management and business processes.',
    founders: [{ id: 1, name: 'Sunny Lu', role: 'CEO', bio: 'Founder and CEO of VeChain.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=SL', socialLinks: { twitter: 'https://twitter.com/sunnylu20' } }],
    news: [{ id: 1, title: 'VeChain Partnerships', content: 'VeChain secures new partnerships for supply chain solutions.', tags: ['Supply Chain'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is VeChain?', answer: 'VeChain is a blockchain platform aimed at improving supply chain management and business processes.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Monero',
    symbol: 'XMR',
    icon: '🔒',
    price: 180.00,
    marketCap: 3.30,
    rank: 28,
    volume24h: 0.08,
    supply: 18.00,
    info: { website: 'https://www.getmonero.org/', whitepaper: '#', blockExplorers: ['https://xmrchain.net/'], github: 'https://github.com/monero-project' },
    about: 'Monero is a secure, private, and untraceable cryptocurrency.',
    founders: [{ id: 1, name: 'Nicolas van Saberhagen', role: 'Creator (Pseudonym)', bio: 'The pseudonymous creator of Monero.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=NV', socialLinks: {} }],
    news: [{ id: 1, title: 'Monero Privacy Features', content: 'Monero continues to enhance its privacy features.', tags: ['Privacy'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Monero?', answer: 'Monero is a decentralized cryptocurrency that is completely private and untraceable.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Polygon',
    symbol: 'MATIC',
    price: 0.75,
    icon: '🟣',
    marketCap: 7.00,
    rank: 12,
    volume24h: 0.45,
    supply: 9.30,
    info: { website: 'https://polygon.technology/', whitepaper: '#', blockExplorers: ['https://polygonscan.com/'], github: 'https://github.com/maticnetwork' },
    about: 'Polygon is a Layer 2 scaling solution for Ethereum, enabling fast, low-cost, and secure transactions.',
    founders: [{ id: 1, name: 'Jaynti Kanani', role: 'Co-founder', bio: 'Co-founder of Polygon.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=JK', socialLinks: {} }],
    news: [{ id: 1, title: 'Polygon zkEVM Launch', content: 'Polygon launches its highly anticipated zkEVM mainnet.', tags: ['zkEVM'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Polygon?', answer: 'Polygon (formerly Matic Network) is a Layer 2 scaling solution for Ethereum.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Arbitrum',
    symbol: 'ARB',
    price: 1.10,
    icon: '🟠',
    marketCap: 2.80,
    rank: 30,
    volume24h: 0.20,
    supply: 2.50,
    info: { website: 'https://arbitrum.io/', whitepaper: '#', blockExplorers: ['https://arbiscan.io/'], github: 'https://github.com/OffchainLabs' },
    about: 'Arbitrum is a Layer 2 scaling solution for Ethereum using optimistic rollups.',
    founders: [{ id: 1, name: 'Offchain Labs', role: 'Developer', bio: 'The team behind Arbitrum.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=OL', socialLinks: {} }],
    news: [{ id: 1, title: 'Arbitrum One Upgrades', content: 'Arbitrum One network receives performance upgrades.', tags: ['Scaling'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Arbitrum?', answer: 'Arbitrum is a suite of Ethereum scaling solutions that enable high-throughput, low-cost dApps.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Optimism',
    symbol: 'OP',
    price: 2.50,
    marketCap: 2.20,
    icon: '🟢',
    rank: 45,
    volume24h: 0.18,
    supply: 2.10,
    info: { website: 'https://www.optimism.io/', whitepaper: '#', blockExplorers: ['https://optimistic.etherscan.io/'], github: 'https://github.com/ethereum-optimism' },
    about: 'Optimism is a low-cost, lightning-fast Ethereum Layer 2 blockchain.',
    founders: [{ id: 1, name: 'Optimism Foundation', role: 'Developer', bio: 'The team behind Optimism.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=OF', socialLinks: {} }],
    news: [{ id: 1, title: 'Optimism Bedrock Upgrade', content: 'Optimism successfully completes its Bedrock upgrade.', tags: ['Upgrade'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Optimism?', answer: 'Optimism is an Ethereum Layer 2 scaling solution that uses optimistic rollups to process transactions faster and cheaper.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Dogecoin',
    symbol: 'DOGE',
    icon: '🐶',
    price: 0.12,
    marketCap: 17.00,
    rank: 8,
    volume24h: 0.80,
    supply: 140.00,
    info: { website: 'https://dogecoin.com/', whitepaper: '#', blockExplorers: ['https://dogechain.info/'], github: 'https://github.com/dogecoin/dogecoin' },
    about: 'Dogecoin is a decentralized, peer-to-peer digital currency that enables you to send money online.',
    founders: [{ id: 1, name: 'Billy Markus', role: 'Co-founder', bio: 'Software engineer and co-creator of Dogecoin.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=BM', socialLinks: { twitter: 'https://twitter.com/BillyM2k' } }],
    news: [{ id: 1, title: 'DOGE on the Moon', content: 'Elon Musk continues to tweet about Dogecoin.', tags: ['Meme Coin'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Dogecoin?', answer: 'Dogecoin is an open-source, peer-to-peer digital currency, favored by Shiba Inus worldwide.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Shiba Inu',
    symbol: 'SHIB',
    price: 0.000025,
    marketCap: 15.00,
    rank: 11,
    volume24h: 0.60,
    supply: 589.00,
    info: { website: 'https://shibatoken.com/', whitepaper: '#', blockExplorers: ['https://etherscan.io/token/0x95aD61b0a150d79219dCEa232c6dBC046B60aBCA'], github: 'https://github.com/shytoshikusama' },
    about: 'Shiba Inu is a decentralized cryptocurrency created in August 2020 by an anonymous developer known as "Ryoshi."',
    founders: [{ id: 1, name: 'Ryoshi', role: 'Creator (Anonymous)', bio: 'The anonymous creator of Shiba Inu.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=RY', socialLinks: {} }],
    news: [{ id: 1, title: 'ShibaSwap Updates', content: 'ShibaSwap decentralized exchange gets new features.', tags: ['DeFi'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Shiba Inu?', answer: 'Shiba Inu (SHIB) is a decentralized cryptocurrency that emerged as a Dogecoin-inspired meme coin.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Dai',
    symbol: 'DAI',
    price: 1.00,
    marketCap: 5.00,
    rank: 19,
    volume24h: 0.30,
    supply: 5.00,
    info: { website: 'https://makerdao.com/en/', whitepaper: '#', blockExplorers: ['https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f'], github: 'https://github.com/makerdao' },
    about: 'Dai is a decentralized, unbiased, collateral-backed cryptocurrency soft-pegged to the US Dollar.',
    founders: [{ id: 1, name: 'Rune Christensen', role: 'Founder', bio: 'Founder of MakerDAO, the creator of Dai.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=RC', socialLinks: { twitter: 'https://twitter.com/RuneKek' } }],
    news: [{ id: 1, title: 'Dai Stability', content: 'Dai maintains its peg amidst market volatility.', tags: ['Stablecoin'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Dai?', answer: 'Dai is a decentralized stablecoin that aims to maintain a stable value against the US dollar.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Uniswap',
    symbol: 'UNI',
    price: 8.00,
    marketCap: 4.80,
    rank: 22,
    volume24h: 0.25,
    supply: 600.00,
    info: { website: 'https://uniswap.org/', whitepaper: '#', blockExplorers: ['https://etherscan.io/token/0x1f9840a85d5af5bf1d1762f925bdaddc4201f984'], github: 'https://github.com/Uniswap' },
    about: 'Uniswap is a decentralized exchange (DEX) protocol that facilitates automated transactions between cryptocurrency tokens on the Ethereum blockchain.',
    founders: [{ id: 1, name: 'Hayden Adams', role: 'Founder', bio: 'Creator of Uniswap.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=HA', socialLinks: { twitter: 'https://twitter.com/haydenzadams' } }],
    news: [{ id: 1, title: 'Uniswap V3 Launch', content: 'Uniswap launches its highly anticipated V3 protocol.', tags: ['DEX'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Uniswap?', answer: 'Uniswap is a decentralized exchange protocol built on Ethereum that allows users to swap ERC-20 tokens without intermediaries.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Aave',
    symbol: 'AAVE',
    price: 100.00,
    marketCap: 1.50,
    rank: 38,
    volume24h: 0.10,
    supply: 16.00,
    info: { website: 'https://aave.com/', whitepaper: '#', blockExplorers: ['https://etherscan.io/token/0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddf06'], github: 'https://github.com/aave' },
    about: 'Aave is a decentralized non-custodial liquidity protocol where users can participate as depositors or borrowers.',
    founders: [{ id: 1, name: 'Stani Kulechov', role: 'Founder', bio: 'Founder and CEO of Aave.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=SK', socialLinks: { twitter: 'https://twitter.com/StaniKulechov' } }],
    news: [{ id: 1, title: 'Aave V3 Launch', content: 'Aave launches its V3 protocol with new features.', tags: ['DeFi'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Aave?', answer: 'Aave is a decentralized finance (DeFi) protocol that allows users to lend and borrow cryptocurrencies.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Compound',
    symbol: 'COMP',
    price: 50.00,
    marketCap: 0.50,
    rank: 60,
    volume24h: 0.05,
    supply: 10.00,
    info: { website: 'https://compound.finance/', whitepaper: '#', blockExplorers: ['https://etherscan.io/token/0xc00e94cb662c3520282e6f5717214004a7f26888'], github: 'https://github.com/compound-finance' },
    about: 'Compound is a decentralized finance (DeFi) protocol that allows users to earn interest on their cryptocurrencies or borrow assets against collateral.',
    founders: [{ id: 1, name: 'Robert Leshner', role: 'Founder', bio: 'Founder and CEO of Compound Labs.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=RL', socialLinks: { twitter: 'https://twitter.com/rleshner' } }],
    news: [{ id: 1, title: 'Compound Governance', content: 'Compound governance proposals are actively debated.', tags: ['DeFi'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Compound?', answer: 'Compound is a decentralized lending protocol on the Ethereum blockchain.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Synthetix',
    symbol: 'SNX',
    price: 3.00,
    marketCap: 0.90,
    rank: 70,
    volume24h: 0.03,
    supply: 300.00,
    info: { website: 'https://synthetix.io/', whitepaper: '#', blockExplorers: ['https://etherscan.io/token/0xc011a73ee8576fb46f5e1c5751a46d942b0ee878'], github: 'https://github.com/Synthetixio' },
    about: 'Synthetix is a decentralized synthetic asset issuance protocol built on Ethereum.',
    founders: [{ id: 1, name: 'Kain Warwick', role: 'Founder', bio: 'Founder of Synthetix.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=KW', socialLinks: { twitter: 'https://twitter.com/kaiynne' } }],
    news: [{ id: 1, title: 'Synthetix Atomic Swaps', content: 'Synthetix introduces atomic swaps for synthetic assets.', tags: ['DeFi'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Synthetix?', answer: 'Synthetix is a decentralized synthetic asset platform on Ethereum.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Yearn Finance',
    symbol: 'YFI',
    price: 7000.00,
    marketCap: 0.25,
    rank: 80,
    volume24h: 0.01,
    supply: 36.60,
    info: { website: 'https://yearn.finance/', whitepaper: '#', blockExplorers: ['https://etherscan.io/token/0x0bc529c00c6401aef6d220be8c6ea7ad19a377df'], github: 'https://github.com/yearn' },
    about: 'Yearn Finance is a decentralized finance (DeFi) aggregator service that optimizes yield farming for users.',
    founders: [{ id: 1, name: 'Andre Cronje', role: 'Founder', bio: 'Creator of Yearn Finance.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=AC', socialLinks: { twitter: 'https://twitter.com/AndreCronjeTech' } }],
    news: [{ id: 1, title: 'Yearn V3 Development', content: 'Yearn Finance announces development of V3 vaults.', tags: ['DeFi'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Yearn Finance?', answer: 'Yearn Finance is a decentralized finance (DeFi) platform that aims to simplify yield farming for users.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Fantom',
    symbol: 'FTM',
    price: 0.30,
    marketCap: 0.80,
    rank: 65,
    volume24h: 0.04,
    supply: 3.10,
    info: { website: 'https://fantom.foundation/', whitepaper: '#', blockExplorers: ['https://ftmscan.com/'], github: 'https://github.com/Fantom-Foundation' },
    about: 'Fantom is a fast, high-throughput open-source smart contract platform for digital assets and dApps.',
    founders: [{ id: 1, name: 'Ahn Byung Ik', role: 'Founder', bio: 'South Korean computer scientist and founder of Fantom.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=AI', socialLinks: {} }],
    news: [{ id: 1, title: 'Fantom Ecosystem Grants', content: 'Fantom Foundation announces new grants for developers.', tags: ['Grants'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Fantom?', answer: 'Fantom is a high-performance, scalable, and secure smart-contract platform.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Decentraland',
    symbol: 'MANA',
    price: 0.40,
    marketCap: 0.75,
    rank: 75,
    volume24h: 0.02,
    supply: 1.80,
    info: { website: 'https://decentraland.org/', whitepaper: '#', blockExplorers: ['https://etherscan.io/token/0x0f5d2fb29fb7d3cfee4449514cfb3d8d124bb0bc'], github: 'https://github.com/decentraland' },
    about: 'Decentraland is a decentralized virtual reality platform powered by the Ethereum blockchain.',
    founders: [{ id: 1, name: 'Ari Meilich', role: 'Co-founder', bio: 'Co-founder of Decentraland.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=AM', socialLinks: { twitter: 'https://twitter.com/arimeilich' } }],
    news: [{ id: 1, title: 'Metaverse Events', content: 'Decentraland hosts major metaverse events.', tags: ['Metaverse'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Decentraland?', answer: 'Decentraland is a virtual reality platform powered by the Ethereum blockchain, where users can create, experience, and monetize content and applications.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'The Sandbox',
    symbol: 'SAND',
    price: 0.50,
    marketCap: 1.00,
    rank: 50,
    volume24h: 0.03,
    supply: 2.00,
    info: { website: 'https://www.sandbox.game/en/', whitepaper: '#', blockExplorers: ['https://etherscan.io/token/0x3845badade8e6dff049820680d1fcd19a963e5d0'], github: 'https://github.com/thesandboxgame' },
    about: 'The Sandbox is a blockchain-based virtual world allowing users to create, build, buy and sell digital assets in the form of a game.',
    founders: [{ id: 1, name: 'Arthur Madrid', role: 'Co-founder', bio: 'Co-founder of The Sandbox.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=AM', socialLinks: { twitter: 'https://twitter.com/arthurmadrid' } }],
    news: [{ id: 1, title: 'Sandbox Alpha Season', content: 'The Sandbox launches new Alpha seasons with exclusive content.', tags: ['Metaverse'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is The Sandbox?', answer: 'The Sandbox is a virtual metaverse where players can build, own, and monetize their gaming experiences on the Ethereum blockchain.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Axie Infinity',
    symbol: 'AXS',
    price: 6.00,
    marketCap: 0.80,
    rank: 68,
    volume24h: 0.05,
    supply: 270.00,
    info: { website: 'https://axieinfinity.com/', whitepaper: '#', blockExplorers: ['https://etherscan.io/token/0xbb0e17ef654109c26bb7ab02101e54e2a7a2f4a4'], github: 'https://github.com/axieinfinity' },
    about: 'Axie Infinity is a blockchain-based trading and battling game that is partially owned and operated by its players.',
    founders: [{ id: 1, name: 'Trung Nguyen', role: 'CEO', bio: 'CEO and co-founder of Sky Mavis, the company behind Axie Infinity.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=TN', socialLinks: { twitter: 'https://twitter.com/trungfinity' } }],
    news: [{ id: 1, title: 'Axie Origin Launch', content: 'Axie Infinity launches its new battle system, Origin.', tags: ['GameFi'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Axie Infinity?', answer: 'Axie Infinity is a blockchain-based game where players can breed, raise, battle, and trade NFT creatures called Axies.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Theta Network',
    symbol: 'THETA',
    price: 1.00,
    marketCap: 1.00,
    rank: 58,
    volume24h: 0.02,
    supply: 1.00,
    info: { website: 'https://www.thetanetwork.org/', whitepaper: '#', blockExplorers: ['https://explorer.thetatoken.org/'], github: 'https://github.com/thetatoken' },
    about: 'Theta Network is a decentralized video delivery network, powered by users, for users.',
    founders: [{ id: 1, name: 'Mitch Liu', role: 'Co-founder', bio: 'Co-founder and CEO of Theta Labs.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=ML', socialLinks: { twitter: 'https://twitter.com/mitchliu' } }],
    news: [{ id: 1, title: 'Theta Mainnet 3.0', content: 'Theta Network launches its highly anticipated Mainnet 3.0.', tags: ['Video'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Theta Network?', answer: 'Theta Network is a decentralized video delivery network that aims to revolutionize the video streaming industry.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Filecoin',
    symbol: 'FIL',
    price: 5.00,
    marketCap: 2.50,
    rank: 32,
    volume24h: 0.15,
    supply: 500.00,
    info: { website: 'https://filecoin.io/', whitepaper: '#', blockExplorers: ['https://filfox.info/en'], github: 'https://github.com/filecoin-project' },
    about: 'Filecoin is a decentralized storage network that allows users to store, retrieve, and host digital information.',
    founders: [{ id: 1, name: 'Juan Benet', role: 'Founder', bio: 'Founder of Protocol Labs, the company behind Filecoin and IPFS.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=JB', socialLinks: { twitter: 'https://twitter.com/juanbenet' } }],
    news: [{ id: 1, title: 'Filecoin Storage Growth', content: 'Filecoin network sees significant growth in storage capacity.', tags: ['Storage'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Filecoin?', answer: 'Filecoin is a decentralized storage network that aims to store humanity\'s most important information.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Hedera',
    symbol: 'HBAR',
    price: 0.08,
    marketCap: 2.80,
    rank: 31,
    volume24h: 0.05,
    supply: 35.00,
    info: { website: 'https://hedera.com/', whitepaper: '#', blockExplorers: ['https://hashscan.io/'], github: 'https://github.com/hashgraph' },
    about: 'Hedera is a public distributed ledger for building and deploying decentralized applications.',
    founders: [{ id: 1, name: 'Dr. Leemon Baird', role: 'Co-founder', bio: 'Inventor of the Hashgraph distributed consensus algorithm.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=LB', socialLinks: { twitter: 'https://twitter.com/leemonbaird' } }],
    news: [{ id: 1, title: 'Hedera Enterprise Solutions', content: 'Hedera gains traction with enterprise-grade solutions.', tags: ['Enterprise'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Hedera?', answer: 'Hedera is a decentralized public network built on the Hashgraph consensus algorithm.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Algorand',
    symbol: 'ALGO',
    price: 0.15,
    marketCap: 1.20,
    rank: 48,
    volume24h: 0.08,
    supply: 8.00,
    info: { website: 'https://www.algorand.com/', whitepaper: '#', blockExplorers: ['https://algoexplorer.io/'], github: 'https://github.com/algorand' },
    about: 'Algorand is a decentralized, secure, and scalable blockchain platform that supports smart contracts.',
    founders: [{ id: 1, name: 'Silvio Micali', role: 'Founder', bio: 'Turing Award-winning cryptographer and founder of Algorand.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=SM', socialLinks: {} }],
    news: [{ id: 1, title: 'Algorand DeFi Growth', content: 'Algorand\'s DeFi ecosystem continues to expand.', tags: ['DeFi'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Algorand?', answer: 'Algorand is a decentralized, secure, and scalable blockchain that provides a common platform for building products and services.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Tezos',
    symbol: 'XTZ',
    price: 0.80,
    marketCap: 0.70,
    rank: 72,
    volume24h: 0.02,
    supply: 950.00,
    info: { website: 'https://tezos.com/', whitepaper: '#', blockExplorers: ['https://tzstats.com/'], github: 'https://github.com/tezos' },
    about: 'Tezos is an open-source platform for assets and applications, featuring a modular architecture and formal verification.',
    founders: [{ id: 1, name: 'Arthur Breitman', role: 'Co-founder', bio: 'Co-founder of Tezos.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=AB', socialLinks: { twitter: 'https://twitter.com/ArthurB' } }],
    news: [{ id: 1, title: 'Tezos NFT Market', content: 'Tezos NFT market sees significant growth and adoption.', tags: ['NFT'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Tezos?', answer: 'Tezos is a decentralized, open-source blockchain network that can execute peer-to-peer transactions and serve as a platform for deploying smart contracts.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'EOS',
    symbol: 'EOS',
    price: 0.70,
    marketCap: 0.70,
    rank: 78,
    volume24h: 0.03,
    supply: 1.00,
    info: { website: 'https://eos.io/', whitepaper: '#', blockExplorers: ['https://bloks.io/'], github: 'https://github.com/EOSIO' },
    about: 'EOS is a blockchain platform designed for the development of decentralized applications (dApps).',
    founders: [{ id: 1, name: 'Brendan Blumer', role: 'CEO', bio: 'CEO of Block.one, the company behind EOSIO.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=BB', socialLinks: { twitter: 'https://twitter.com/BrendanBlumer' } }],
    news: [{ id: 1, title: 'EOS Network Foundation', content: 'EOS Network Foundation drives ecosystem growth.', tags: ['Ecosystem'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is EOS?', answer: 'EOS is a blockchain platform that aims to provide a decentralized operating system for dApps.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Zcash',
    symbol: 'ZEC',
    price: 35.00,
    marketCap: 0.55,
    rank: 85,
    volume24h: 0.02,
    supply: 16.00,
    info: { website: 'https://z.cash/', whitepaper: '#', blockExplorers: ['https://zcash.blockchair.com/'], github: 'https://github.com/zcash' },
    about: 'Zcash is a privacy-preserving cryptocurrency that uses zero-knowledge proofs to enable confidential transactions.',
    founders: [{ id: 1, name: 'Zooko Wilcox-O\'Hearn', role: 'Founder', bio: 'Founder of Zcash and CEO of Electric Coin Company.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=ZW', socialLinks: { twitter: 'https://twitter.com/zooko' } }],
    news: [{ id: 1, title: 'Zcash Privacy Upgrades', content: 'Zcash implements new privacy-enhancing upgrades.', tags: ['Privacy'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Zcash?', answer: 'Zcash is a decentralized cryptocurrency that offers optional privacy and transparency of transactions.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Dash',
    symbol: 'DASH',
    price: 30.00,
    marketCap: 0.35,
    rank: 90,
    volume24h: 0.01,
    supply: 11.00,
    info: { website: 'https://www.dash.org/', whitepaper: '#', blockExplorers: ['https://chain.so/DASH'], github: 'https://github.com/dashpay' },
    about: 'Dash is an open-source cryptocurrency focused on offering a fast, private, and secure payment method.',
    founders: [{ id: 1, name: 'Evan Duffield', role: 'Creator', bio: 'Creator of Dash.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=ED', socialLinks: { twitter: 'https://twitter.com/evanduffield' } }],
    news: [{ id: 1, title: 'Dash Evolution', content: 'Dash continues development on its Evolution platform.', tags: ['Payments'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Dash?', answer: 'Dash is an open-source cryptocurrency that offers instant transactions (InstantSend), private transactions (PrivateSend), and a decentralized governance system (DGBB).' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Neo',
    symbol: 'NEO',
    price: 10.00,
    marketCap: 0.70,
    rank: 73,
    volume24h: 0.03,
    supply: 70.00,
    info: { website: 'https://neo.org/', whitepaper: '#', blockExplorers: ['https://neotube.io/'], github: 'https://github.com/neo-project' },
    about: 'Neo is an open-source blockchain platform that aims to build a "smart economy" with digital assets, digital identity, and smart contracts.',
    founders: [{ id: 1, name: 'Da Hongfei', role: 'Co-founder', bio: 'Co-founder of Neo and CEO of Onchain.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=DH', socialLinks: { twitter: 'https://twitter.com/dahongfei' } }],
    news: [{ id: 1, title: 'Neo N3 Mainnet', content: 'Neo N3 mainnet brings new features and improvements.', tags: ['Upgrade'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Neo?', answer: 'Neo is an open-source, community-driven blockchain platform.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'IOTA',
    symbol: 'MIOTA',
    price: 0.25,
    marketCap: 0.70,
    rank: 74,
    volume24h: 0.02,
    supply: 2.70,
    info: { website: 'https://www.iota.org/', whitepaper: '#', blockExplorers: ['https://explorer.iota.org/'], github: 'https://github.com/iotaledger' },
    about: 'IOTA is a distributed ledger technology (DLT) designed for the Internet of Things (IoT).',
    founders: [{ id: 1, name: 'David Sønstebø', role: 'Co-founder', bio: 'Co-founder of IOTA.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=DS', socialLinks: { twitter: 'https://twitter.com/DavidSonstebo' } }],
    news: [{ id: 1, title: 'IOTA Shimmer Network', content: 'IOTA launches its Shimmer network for innovation.', tags: ['IoT'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is IOTA?', answer: 'IOTA is a distributed ledger technology (DLT) that uses a directed acyclic graph (DAG) called Tangle instead of a blockchain.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Qtum',
    symbol: 'QTUM',
    price: 2.00,
    marketCap: 0.20,
    rank: 100,
    volume24h: 0.01,
    supply: 100.00,
    info: { website: 'https://qtum.org/', whitepaper: '#', blockExplorers: ['https://qtum.info/'], github: 'https://github.com/qtumproject' },
    about: 'Qtum is a decentralized blockchain application platform that combines the UTXO model of Bitcoin with the smart contract capabilities of Ethereum.',
    founders: [{ id: 1, name: 'Patrick Dai', role: 'Founder', bio: 'Founder of Qtum.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=PD', socialLinks: { twitter: 'https://twitter.com/PatrickXDai' } }],
    news: [{ id: 1, title: 'Qtum Mainnet Updates', content: 'Qtum mainnet receives new updates and features.', tags: ['Platform'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Qtum?', answer: 'Qtum is a decentralized blockchain application platform that aims to bridge the gap between Bitcoin and Ethereum.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Zilliqa',
    symbol: 'ZIL',
    price: 0.02,
    marketCap: 0.30,
    rank: 95,
    volume24h: 0.01,
    supply: 16.00,
    info: { website: 'https://www.zilliqa.com/', whitepaper: '#', blockExplorers: ['https://viewblock.io/zilliqa'], github: 'https://github.com/Zilliqa' },
    about: 'Zilliqa is a high-performance, high-security blockchain platform designed to scale to thousands of transactions per second through sharding.',
    founders: [{ id: 1, name: 'Xinshu Dong', role: 'Co-founder', bio: 'Co-founder of Zilliqa.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=XD', socialLinks: { twitter: 'https://twitter.com/xinshudong' } }],
    news: [{ id: 1, title: 'Zilliqa Metaverse Plans', content: 'Zilliqa announces plans for metaverse expansion.', tags: ['Metaverse'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Zilliqa?', answer: 'Zilliqa is a public blockchain platform designed to scale to thousands of transactions per second through sharding.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Elrond',
    symbol: 'EGLD',
    price: 40.00,
    marketCap: 1.00,
    rank: 52,
    volume24h: 0.05,
    supply: 25.00,
    info: { website: 'https://elrond.com/', whitepaper: '#', blockExplorers: ['https://explorer.elrond.com/'], github: 'https://github.com/ElrondNetwork' },
    about: 'Elrond is a highly scalable, fast, and secure blockchain platform for distributed apps, enterprise use cases, and the new internet economy.',
    founders: [{ id: 1, name: 'Beniamin Mincu', role: 'CEO', bio: 'CEO and co-founder of Elrond.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=BM', socialLinks: { twitter: 'https://twitter.com/beniaminmincu' } }],
    news: [{ id: 1, title: 'Elrond Mainnet Upgrade', content: 'Elrond network undergoes significant mainnet upgrades.', tags: ['Upgrade'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Elrond?', answer: 'Elrond is a blockchain platform for the new internet economy, decentralized applications, and enterprise use cases.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Flow',
    symbol: 'FLOW',
    price: 0.70,
    marketCap: 0.70,
    rank: 76,
    volume24h: 0.03,
    supply: 1.40,
    info: { website: 'https://flow.com/', whitepaper: '#', blockExplorers: ['https://flowscan.org/'], github: 'https://github.com/onflow' },
    about: 'Flow is a fast, decentralized, and developer-friendly blockchain designed as the foundation for a new generation of games, apps, and the digital assets that power them.',
    founders: [{ id: 1, name: 'Dapper Labs', role: 'Developer', bio: 'The team behind Flow.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=DL', socialLinks: {} }],
    news: [{ id: 1, title: 'Flow NFT Ecosystem', content: 'Flow\'s NFT ecosystem continues to thrive with new projects.', tags: ['NFT'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Flow?', answer: 'Flow is a fast, decentralized, and developer-friendly blockchain designed for games, apps, and digital assets.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Kusama',
    symbol: 'KSM',
    price: 30.00,
    marketCap: 0.25,
    rank: 98,
    volume24h: 0.01,
    supply: 8.50,
    info: { website: 'https://kusama.network/', whitepaper: '#', blockExplorers: ['https://kusama.subscan.io/'], github: 'https://github.com/paritytech/polkadot' },
    about: 'Kusama is a public pre-production environment for Polkadot, designed to be a canary network.',
    founders: [{ id: 1, name: 'Gavin Wood', role: 'Creator', bio: 'Creator of Polkadot and Kusama.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=GW', socialLinks: { twitter: 'https://twitter.com/gavofyork' } }],
    news: [{ id: 1, title: 'Kusama Parachain Auctions', content: 'Kusama continues its parachain auctions for new projects.', tags: ['Parachains'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Kusama?', answer: 'Kusama is Polkadot\'s canary network, an experimental blockchain environment that allows for early-stage deployment and testing of new features.' }],
    relatedChains: [{ name: 'Polkadot', change: 0.00 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Decentralized Social',
    symbol: 'DESO',
    price: 15.00,
    marketCap: 0.15,
    rank: 120,
    volume24h: 0.005,
    supply: 10.00,
    info: { website: 'https://www.deso.org/', whitepaper: '#', blockExplorers: ['https://explorer.deso.org/'], github: 'https://github.com/deso-protocol' },
    about: 'Decentralized Social (DeSo) is a new layer-1 blockchain built from the ground up to power and scale decentralized social applications.',
    founders: [{ id: 1, name: 'Nader Al-Naji', role: 'Founder', bio: 'Founder of DeSo.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=NA', socialLinks: { twitter: 'https://twitter.com/Nader' } }],
    news: [{ id: 1, title: 'DeSo Social Apps', content: 'New decentralized social applications launch on DeSo.', tags: ['SocialFi'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is DeSo?', answer: 'DeSo is a new layer-1 blockchain designed to decentralize social media.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Harmony',
    symbol: 'ONE',
    price: 0.01,
    marketCap: 0.12,
    rank: 130,
    volume24h: 0.003,
    supply: 12.00,
    info: { website: 'https://www.harmony.one/', whitepaper: '#', blockExplorers: ['https://explorer.harmony.one/'], github: 'https://github.com/harmony-one' },
    about: 'Harmony is an open and fast blockchain with cross-chain compatibility.',
    founders: [{ id: 1, name: 'Stephen Tse', role: 'Founder', bio: 'Founder and CEO of Harmony.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=ST', socialLinks: { twitter: 'https://twitter.com/stse' } }],
    news: [{ id: 1, title: 'Harmony Bridges', content: 'Harmony enhances cross-chain bridges for seamless asset transfers.', tags: ['Cross-chain'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Harmony?', answer: 'Harmony is a fast and open blockchain for decentralized applications.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Celo',
    symbol: 'CELO',
    price: 0.60,
    marketCap: 0.30,
    rank: 96,
    volume24h: 0.01,
    supply: 500.00,
    info: { website: 'https://celo.org/', whitepaper: '#', blockExplorers: ['https://celoscan.io/'], github: 'https://github.com/celo-org' },
    about: 'Celo is a mobile-first blockchain platform that makes financial tools accessible to anyone with a smartphone.',
    founders: [{ id: 1, name: 'Rene Reinsberg', role: 'Co-founder', bio: 'Co-founder of Celo.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=RR', socialLinks: { twitter: 'https://twitter.com/rene_reinsberg' } }],
    news: [{ id: 1, title: 'Celo Mobile Payments', content: 'Celo expands its mobile payment solutions globally.', tags: ['Mobile'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Celo?', answer: 'Celo is a mobile-first blockchain platform that aims to build a financial system that creates conditions of prosperity for all.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Kava',
    symbol: 'KAVA',
    price: 0.80,
    marketCap: 0.25,
    rank: 105,
    volume24h: 0.008,
    supply: 400.00,
    info: { website: 'https://www.kava.io/', whitepaper: '#', blockExplorers: ['https://kava.mintscan.io/'], github: 'https://github.com/Kava-Labs' },
    about: 'Kava is a decentralized finance (DeFi) platform that provides collateralized loans and stablecoins.',
    founders: [{ id: 1, name: 'Brian Kerr', role: 'Co-founder', bio: 'Co-founder and CEO of Kava Labs.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=BK', socialLinks: { twitter: 'https://twitter.com/brian_kerr' } }],
    news: [{ id: 1, title: 'Kava EVM Launch', content: 'Kava launches its Ethereum Virtual Machine (EVM) compatible chain.', tags: ['DeFi'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Kava?', answer: 'Kava is a cross-chain DeFi lending platform that allows users to borrow stablecoins against their crypto assets.' }],
    relatedChains: [{ name: 'BNB Chain', change: -0.02 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Waves',
    symbol: 'WAVES',
    price: 1.50,
    marketCap: 0.15,
    rank: 115,
    volume24h: 0.005,
    supply: 100.00,
    info: { website: 'https://waves.tech/', whitepaper: '#', blockExplorers: ['https://wavesexplorer.com/'], github: 'https://github.com/wavesplatform' },
    about: 'Waves is an open-source blockchain platform that enables users to create custom tokens and decentralized applications.',
    founders: [{ id: 1, name: 'Sasha Ivanov', role: 'Founder', bio: 'Founder of Waves Platform.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=SI', socialLinks: { twitter: 'https://twitter.com/sasha35625' } }],
    news: [{ id: 1, title: 'Waves DAO Governance', content: 'Waves implements new DAO governance model.', tags: ['Governance'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Waves?', answer: 'Waves is an open-source blockchain platform that allows users to create custom tokens and decentralized applications.' }],
    relatedChains: [{ name: 'Ethereum', change: 0.01 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
  {
    name: 'Ontology',
    symbol: 'ONT',
    price: 0.20,
    marketCap: 0.18,
    rank: 110,
    volume24h: 0.007,
    supply: 875.00,
    info: { website: 'https://ont.io/', whitepaper: '#', blockExplorers: ['https://explorer.ont.io/'], github: 'https://github.com/ontio' },
    about: 'Ontology is a high-performance public blockchain project that specializes in digital identity and data.',
    founders: [{ id: 1, name: 'Li Jun', role: 'Founder', bio: 'Founder of Ontology.', imageUrl: 'https://placehold.co/80x80/4A4A4A/FFFFFF?text=LJ', socialLinks: { twitter: 'https://twitter.com/LiJun_Ontology' } }],
    news: [{ id: 1, title: 'Ontology DID Solutions', content: 'Ontology expands its decentralized identity (DID) solutions.', tags: ['Identity'], imageUrl: "https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D" }],
    faqs: [{ id: 1, question: 'What is Ontology?', answer: 'Ontology is a high-performance public blockchain project and distributed trust collaboration platform.' }],
    relatedChains: [{ name: 'Neo', change: 0.03 }],
    backgroundImages: ["https://images.unsplash.com/photo-1621503936934-8c6f11414e21?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmluYW5jZSUyMG5ld3N8ZW58MHx8MHx8fDA%3D"],
  },
];





// Helper function to get chain data by name
export const getChainData = (chainName) => {
  return chainsData.find(chain => chain.name.toLowerCase() === chainName.toLowerCase());
};
