// dappsData.js

export const dappsChainsData = [
  {
    name: 'Ethereum',
    logo: 'https://placehold.co/40x40/4A4A4A/FFFFFF?text=ETH',
    allDapps: [
      { id: 1, name: 'Zapper', description: 'Monitor all your DeFi assets in one place. Track your portfolio, liabilities, and liquidity positions across multiple protocols.', category: 'Portfolio Management', imageUrl: 'https://placehold.co/40x40/5B21B6/FFFFFF?text=ZAP', users: '1.2M', link: 'https://zapper.fi' },
      { id: 2, name: 'FastEx', description: 'Decentralized exchange for fast and secure token swaps on Ethereum.', category: 'Exchange', imageUrl: 'https://placehold.co/40x40/EC4899/FFFFFF?text=FX', users: '800K', link: 'https://www.fastex.io' },
      { id: 3, name: 'MetaLand', description: 'Explore and own virtual land in the metaverse. Build and monetize your digital assets.', category: 'Metaverse', imageUrl: 'https://placehold.co/40x40/10B981/FFFFFF?text=ML', users: '500K', link: 'https://www.metaland.game' },
      { id: 4, name: 'Uniswap', description: 'Leading decentralized exchange for swapping ERC-20 tokens.', category: 'Exchange', imageUrl: 'https://placehold.co/40x40/A855F7/FFFFFF?text=UNI', users: '1.5M', link: 'https://uniswap.org' },
      { id: 5, name: 'Gnosis Safe', description: 'Multi-signature wallet for secure management of crypto assets.', category: 'Wallet', imageUrl: 'https://placehold.co/40x40/4F46E5/FFFFFF?text=GNO', users: '400K', link: 'https://gnosis-safe.io' },
      { id: 6, name: 'DappBuilder', description: 'No-code platform to build and deploy dApps on Ethereum.', category: 'Developer Tools', imageUrl: 'https://placehold.co/40x40/3B82F6/FFFFFF?text=DB', users: '100K', link: 'https://dappbuilder.io' },
      { id: 7, name: 'Umbrella Network', description: 'Decentralized oracle for secure and scalable data feeds.', category: 'Oracle', imageUrl: 'https://placehold.co/40x40/374151/FFFFFF?text=UMB', users: '50K', link: 'https://umbrella.network' },
      { id: 8, name: 'KuCoin', description: 'Centralized exchange with a wide range of cryptocurrencies.', category: 'Centralized Exchange', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=KC', users: '10M', link: 'https://www.kucoin.com' },
      { id: 9, name: 'Gas.zip', description: 'Optimize and reduce Ethereum gas fees for transactions.', category: 'Utility', imageUrl: 'https://placehold.co/40x40/6B7280/FFFFFF?text=GAS', users: '200K', link: 'https://gas.zip' },
      { id: 10, name: 'DAO Foundation', description: 'Tools and resources for building and managing DAOs.', category: 'DAO & Governance', imageUrl: 'https://placehold.co/40x40/EF4444/FFFFFF?text=DAO', users: '80K', link: 'https://daofoundation.org' },
      { id: 11, name: 'Web3DM', description: 'Decentralized data management and storage solutions for Web3.', category: 'Storage', imageUrl: 'https://placehold.co/40x40/FBBF24/000000?text=W3DM', users: '30K', link: 'https://web3dm.io' },
      { id: 12, name: 'Doyls', description: 'Web3 social platform for decentralized communication and content sharing.', category: 'Social', imageUrl: 'https://placehold.co/40x40/A78BFA/FFFFFF?text=DYLS', users: '150K', link: 'https://doyls.xyz' },
      { id: 13, name: 'Vently', description: 'Decentralized event management and ticketing platform.', category: 'Events', imageUrl: 'https://placehold.co/40x40/6366F1/FFFFFF?text=VENT', users: '70K', link: 'https://vently.app' },
      { id: 14, name: 'BICSscan', description: 'Blockchain explorer for BICS Chain, providing real-time data on transactions and blocks.', category: 'Infrastructure', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=BSC', users: '1M', link: 'https://bicsscan.com' },
      { id: 15, name: 'Normal', description: 'A decentralized identity management solution for Web3.', category: 'Identity', imageUrl: 'https://placehold.co/40x40/F87171/FFFFFF?text=NORM', users: '90K', link: 'https://normal.id' },
      { id: 16, name: 'Tendency', description: 'AI-powered trading and analytics platform for decentralized finance.', category: 'Analytics', imageUrl: 'https://placehold.co/40x40/EC4899/FFFFFF?text=TEND', users: '120K', link: 'https://tendency.ai' },
      { id: 17, name: 'Nansen Portfolio', description: 'Advanced blockchain analytics platform for on-chain data and portfolio tracking.', category: 'Analytics', imageUrl: 'https://placehold.co/40x40/3B82F6/FFFFFF?text=NANSEN', users: '250K', link: 'https://www.nansen.ai' },
      { id: 18, name: 'DappRadar', description: 'Discover, track, and analyze decentralized applications.', category: 'Analytics', imageUrl: 'https://placehold.co/40x40/6366F1/FFFFFF?text=DR', users: '1.8M', link: 'https://dappradar.com' },
      { id: 19, name: 'Bybit', description: 'Leading cryptocurrency exchange for spot and derivatives trading.', category: 'Centralized Exchange', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=BYBIT', users: '8M', link: 'https://www.bybit.com' },
      { id: 20, name: 'OKX Wallet', description: 'Secure and versatile cryptocurrency wallet supporting multiple chains.', category: 'Wallet', imageUrl: 'https://placehold.co/40x40/FF7F50/FFFFFF?text=OKX', users: '5M', link: 'https://www.okx.com/web3' },
      { id: 21, name: 'Chainlink', description: 'Decentralized oracle network providing real-world data to smart contracts.', category: 'Oracle', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=LINK', users: 'N/A', link: 'https://chain.link' },
      { id: 22, name: 'Automata Network', description: 'Decentralized service protocol for privacy and censorship resistance in Web3.', category: 'Privacy', imageUrl: 'https://placehold.co/40x40/374151/FFFFFF?text=ATA', users: 'N/A', link: 'https://ata.network' },
      { id: 23, name: 'CR-fund', description: 'Decentralized investment fund for various crypto assets.', category: 'Investment', imageUrl: 'https://placehold.co/40x40/A855F7/FFFFFF?text=CRF', users: '20K', link: 'https://cr-fund.xyz' },
      { id: 24, name: 'The Graph', description: 'Indexing protocol for querying networks like Ethereum and IPFS.', category: 'Infrastructure', imageUrl: 'https://placehold.co/40x40/6366F1/FFFFFF?text=GRT', users: 'N/A', link: 'https://thegraph.com' },
      { id: 25, name: 'Pocket Network', description: 'Decentralized RPC infrastructure for Web3 applications.', category: 'Infrastructure', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=POKT', users: 'N/A', link: 'https://www.pokt.network' },
      { id: 26, name: 'Pali Wallet', description: 'A user-friendly wallet for managing crypto assets and interacting with dApps.', category: 'Wallet', imageUrl: 'https://placehold.co/40x40/008080/FFFFFF?text=PALI', users: '500K', link: 'https://paliwallet.com' },
      { id: 27, name: 'SafePal', description: 'Hardware and software wallet for secure crypto storage.', category: 'Wallet', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=SFP', users: '2M', link: 'https://www.safepal.com' },
      { id: 28, name: 'Trust Wallet', description: 'Multi-coin crypto wallet for decentralized applications.', category: 'Wallet', imageUrl: 'https://placehold.co/40x40/3366FF/FFFFFF?text=TW', users: '20M', link: 'https://trustwallet.com' },
      { id: 29, name: 'MetaMask', description: 'Popular browser extension wallet for Ethereum and EVM chains.', category: 'Wallet', imageUrl: 'https://placehold.co/40x40/FF7F50/FFFFFF?text=MM', users: '30M', link: 'https://metamask.io' },
      { id: 30, name: 'Argent', description: 'Smart wallet for DeFi and NFTs with enhanced security.', category: 'Wallet', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=ARG', users: '100K', link: 'https://www.argent.xyz' },
      { id: 31, name: 'ZkSync Era', description: 'Zero-knowledge rollup for scalable and low-cost Ethereum transactions.', category: 'L2 Rollup', imageUrl: 'https://placehold.co/40x40/6C8EEF/FFFFFF?text=ZK', users: 'N/A', link: 'https://zksync.io' },
      { id: 32, name: 'Arbitrum One', description: 'Optimistic rollup for fast and cheap Ethereum transactions.', category: 'L2 Rollup', imageUrl: 'https://placehold.co/40x40/2B374F/FFFFFF?text=ARB', users: 'N/A', link: 'https://arbitrum.io' },
      { id: 33, name: 'Optimism', description: 'Scalable and low-cost Ethereum L2 using optimistic rollups.', category: 'L2 Rollup', imageUrl: 'https://placehold.co/40x40/FF0420/FFFFFF?text=OP', users: 'N/A', link: 'https://www.optimism.io' },
      { id: 34, name: 'Polygon PoS', description: 'Sidechain for scalable and secure transactions.', category: 'Sidechain', imageUrl: 'https://placehold.co/40x40/8247E5/FFFFFF?text=POLY', users: 'N/A', link: 'https://polygon.technology' },
      { id: 35, name: 'Avalanche C-Chain', description: 'EVM-compatible blockchain for dApps.', category: 'EVM Chain', imageUrl: 'https://placehold.co/40x40/E84142/FFFFFF?text=AVAX', users: 'N/A', link: 'https://www.avax.network' },
      { id: 36, name: 'Base Network', description: 'Secure, low-cost, developer-friendly Ethereum L2 incubated by Coinbase.', category: 'L2 Rollup', imageUrl: 'https://placehold.co/40x40/0052FF/FFFFFF?text=BASE', users: 'N/A', link: 'https://base.org' },
    ],
    categories: ['Wallet', 'Infrastructure', 'Dapp Tools', 'Developer Tools', 'DAO & Governance', 'On/Off Ramps', 'Security', 'Centralized Exchanges', 'Digital ID', 'Analytics', 'Metaverse', 'Events', 'Privacy', 'L2 Rollup', 'Sidechain', 'EVM Chain'],
  },
  {
    name: 'Binance',
    logo: 'https://placehold.co/40x40/F3BA2F/FFFFFF?text=BNB',
    allDapps: [
      { id: 1, name: 'PancakeSwap', description: 'Leading decentralized exchange on BNB Chain.', category: 'Exchange', imageUrl: 'https://placehold.co/40x40/D29B4D/FFFFFF?text=CAKE', users: '2M', link: 'https://pancakeswap.finance' },
      { id: 2, name: 'Venus Protocol', description: 'Decentralized money market and stablecoin.', category: 'Lending', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=XVS', users: '700K', link: 'https://venus.io' },
      { id: 3, name: 'BakerySwap', description: 'AMM DEX, NFT Marketplace, and GameFi.', category: 'Exchange', imageUrl: 'https://placehold.co/40x40/FF6347/FFFFFF?text=BKS', users: '400K', link: 'https://www.bakeryswap.org' },
      { id: 4, name: 'ApeSwap', description: 'AMM, Yield Farming, and Staking on BNB Chain.', category: 'Exchange', imageUrl: 'https://placehold.co/40x40/FFD700/000000?text=BANANA', users: '350K', link: 'https://apeswap.finance' },
      { id: 5, name: 'Mobox', description: 'GameFi platform with NFTs and yield farming.', category: 'GameFi', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=MBOX', users: '200K', link: 'https://www.mobox.io' },
      { id: 6, name: 'Bomb Crypto', description: 'Play-to-earn game.', category: 'GameFi', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=BCOIN', users: '180K', link: 'https://bombcrypto.io' },
      { id: 7, name: 'Galleria', description: 'Binance NFT Marketplace.', category: 'NFT Marketplace', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=GAL', users: '150K', link: 'https://www.binance.com/en/nft/marketplace' },
      { id: 8, name: 'Element Market', description: 'Multi-chain NFT marketplace.', category: 'NFT Marketplace', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=ELEM', users: '120K', link: 'https://www.element.market' },
      { id: 9, name: 'MDEX', description: 'DEX with AMM and yield farming.', category: 'Exchange', imageUrl: 'https://placehold.co/40x40/FF0000/FFFFFF?text=MDX', users: '600K', link: 'https://mdex.com' },
      { id: 10, name: 'Biswap', description: 'DEX with low trading fees and high rewards.', category: 'Exchange', imageUrl: 'https://placehold.co/40x40/FFD700/000000?text=BSW', users: '550K', link: 'https://biswap.org' },
      { id: 11, name: 'Alpaca Finance', description: 'Leveraged yield farming.', category: 'Lending', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=ALPACA', users: '300K', link: 'https://www.alpaca.finance' },
      { id: 12, name: 'Trust Wallet', description: 'Multi-coin crypto wallet for decentralized applications.', category: 'Wallet', imageUrl: 'https://placehold.co/40x40/3366FF/FFFFFF?text=TW', users: '20M', link: 'https://trustwallet.com' },
      { id: 13, name: 'MetaMask', description: 'Popular browser extension wallet for Ethereum and EVM chains.', category: 'Wallet', imageUrl: 'https://placehold.co/40x40/FF7F50/FFFFFF?text=MM', users: '30M', link: 'https://metamask.io' },
      { id: 14, name: 'Binance Bridge', description: 'Official bridge for transferring assets to and from BNB Chain.', category: 'Bridge', imageUrl: 'https://placehold.co/40x40/F3BA2F/000000?text=BNB', users: 'N/A', link: 'https://www.binance.org/en/bridge' },
      { id: 15, name: 'BSCScan', description: 'Blockchain explorer for BNB Chain.', category: 'Infrastructure', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=BSC', users: 'N/A', link: 'https://bscscan.com' },
      { id: 16, name: 'CoinMarketCap', description: 'Cryptocurrency market capitalization and price tracking.', category: 'Analytics', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=CMC', users: 'N/A', link: 'https://coinmarketcap.com' },
    ],
    categories: ['Wallets', 'Infrastructure', 'Dapp Tools', 'Developer Tools', 'DAO & Governance', 'On/Off Ramps', 'Security', 'Centralized Exchanges', 'Digital ID', 'Exchange', 'Lending', 'GameFi', 'NFT Marketplace', 'Bridge', 'Analytics'],
  },
  {
    name: 'Solana',
    logo: 'https://placehold.co/40x40/00FF00/000000?text=SOL',
    allDapps: [
      { id: 1, name: 'Raydium', description: 'AMM and liquidity provider on Solana.', category: 'Exchange', imageUrl: 'https://placehold.co/40x40/9945FF/FFFFFF?text=RAY', users: '800K', link: 'https://raydium.io' },
      { id: 2, name: 'Magic Eden', description: 'Leading NFT marketplace on Solana.', category: 'NFT Marketplace', imageUrl: 'https://placehold.co/40x40/1C1C1C/FFFFFF?text=ME', users: '600K', link: 'https://magiceden.io' },
      { id: 3, name: 'Orca', description: 'User-friendly AMM on Solana.', category: 'Exchange', imageUrl: 'https://placehold.co/40x40/20C997/FFFFFF?text=ORCA', users: '400K', link: 'https://www.orca.so' },
      { id: 4, name: 'Solend', description: 'Decentralized lending and borrowing protocol.', category: 'Lending', imageUrl: 'https://placehold.co/40x40/00BFFF/FFFFFF?text=SLND', users: '250K', link: 'https://solend.fi' },
      { id: 5, name: 'STEPN', description: 'Move-to-earn game.', category: 'GameFi', imageUrl: 'https://placehold.co/40x40/FFD700/000000?text=GMT', users: '180K', link: 'https://stepn.com' },
      { id: 6, name: 'Star Atlas', description: 'Metaverse gaming experience.', category: 'GameFi', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=ATLAS', users: '100K', link: 'https://staratlas.com' },
      { id: 7, name: 'Marinade Finance', description: 'Liquid staking for SOL.', category: 'Liquid Staking', imageUrl: 'https://placehold.co/40x40/FF4500/FFFFFF?text=MNDE', users: '150K', link: 'https://marinade.finance' },
      { id: 8, name: 'BlazeStake', description: 'Liquid staking on Solana.', category: 'Liquid Staking', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=BLZE', users: '80K', link: 'https://stake.solblaze.org' },
      { id: 9, name: 'Wormhole', description: 'Cross-chain bridge for Solana ecosystem.', category: 'Bridge', imageUrl: 'https://placehold.co/40x40/9945FF/FFFFFF?text=WORM', users: 'N/A', link: 'https://wormhole.com' },
      { id: 10, name: 'Allbridge', description: 'Universal blockchain bridge.', category: 'Bridge', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=ABR', users: 'N/A', link: 'https://allbridge.io' },
      { id: 11, name: 'Serum', description: 'Decentralized exchange protocol.', category: 'Exchange', imageUrl: 'https://placehold.co/40x40/00FF00/000000?text=SRM', users: '700K', link: 'https://www.projectserum.com' },
      { id: 12, name: 'Mango Markets', description: 'Decentralized cross-margin trading.', category: 'Exchange', imageUrl: 'https://placehold.co/40x40/FF4500/FFFFFF?text=MNGO', users: '300K', link: 'https://mango.markets' },
      { id: 13, name: 'Apricot Finance', description: 'Lending and borrowing with leveraged yield farming.', category: 'Lending', imageUrl: 'https://placehold.co/40x40/FFD700/000000?text=APRT', users: '120K', link: 'https://apricot.one' },
      { id: 14, name: 'Jupiter Aggregator', description: 'DEX aggregator for best swap rates.', category: 'Exchange', imageUrl: 'https://placehold.co/40x40/800080/FFFFFF?text=JUP', users: '900K', link: 'https://jup.ag' },
      { id: 15, name: 'Solanart', description: 'Solana NFT marketplace.', category: 'NFT Marketplace', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=SOLANART', users: '200K', link: 'https://solanart.io' },
      { id: 16, name: 'Phantom Wallet', description: 'Popular non-custodial wallet for Solana.', category: 'Wallet', imageUrl: 'https://placehold.co/40x40/512DA8/FFFFFF?text=PH', users: '3M', link: 'https://phantom.app' },
      { id: 17, name: 'Solscan', description: 'Blockchain explorer for Solana.', category: 'Infrastructure', imageUrl: 'https://placehold.co/40x40/000000/FFFFFF?text=SOLSCAN', users: 'N/A', link: 'https://solscan.io' },
      { id: 18, name: 'Solana Program Library (SPL)', description: 'Collection of on-chain programs for Solana.', category: 'Developer Tools', imageUrl: 'https://placehold.co/40x40/00FF00/000000?text=SPL', users: 'N/A', link: 'https://spl.solana.com' },
    ],
    categories: ['Wallets', 'Infrastructure', 'Dapp Tools', 'Developer Tools', 'DAO & Governance', 'On/Off Ramps', 'Security', 'Centralized Exchanges', 'Digital ID', 'Exchange', 'Lending', 'GameFi', 'NFT Marketplace', 'Liquid Staking', 'Bridge'],
  },
];

export const getDappsChainData = (chainName) => {
  return dappsChainsData.find(chain => chain.name.toLowerCase() === chainName.toLowerCase());
};
