// pressReleaseData.js

export const pressReleaseChainsData = [
  {
    name: 'Ethereum',
    logo: 'https://placehold.co/40x40/4A4A4A/FFFFFF?text=ETH',
    releases: [
      {
        id: 1,
        title: 'Ethereum Foundation Announces Major Grant Recipients for Q2',
        date: '2024-06-15',
        type: 'Press Release',
        content: 'The Ethereum Foundation has revealed the latest recipients of its grant program, funding key infrastructure and research projects aimed at advancing the Ethereum ecosystem. This round focuses heavily on Layer 2 scaling solutions and privacy-enhancing technologies.',
        sentiment: 'positive',
        impactScore: 4,
        tags: ['Grants', 'Foundation', 'L2', 'Privacy'],
      },
      {
        id: 2,
        title: 'New DeFi Protocol Launches on Ethereum, Offers High Yields',
        date: '2024-06-10',
        type: 'Market Release',
        content: 'A new decentralized finance (DeFi) protocol, "YieldMax," has launched on the Ethereum mainnet, promising innovative yield farming strategies and high APYs for liquidity providers. Initial audits show promising security features.',
        sentiment: 'positive',
        impactScore: 5,
        tags: ['DeFi', 'Yield Farming', 'Launch'],
      },
      {
        id: 3,
        title: 'Ethereum Gas Fees See Temporary Spike Due to NFT Mint',
        date: '2024-06-08',
        type: 'Market Release',
        content: 'Ethereum network experienced a brief but significant surge in gas fees today, attributed to the highly anticipated mint of the "CryptoPunks V2" NFT collection. This highlights continued demand for block space.',
        sentiment: 'negative',
        impactScore: 3,
        tags: ['Gas Fees', 'NFT', 'Network Congestion'],
      },
      {
        id: 4,
        title: 'ConsenSys Releases Q2 Ethereum Developer Report',
        date: '2024-06-01',
        type: 'Press Release',
        content: 'ConsenSys has published its quarterly report on Ethereum developer activity, indicating robust growth in smart contract deployments and active developer addresses. The report emphasizes the increasing adoption of Web3 tools.',
        sentiment: 'positive',
        impactScore: 4,
        tags: ['Developer', 'Report', 'Web3'],
      },
      {
        id: 5,
        title: 'Major Exchange Integrates More Ethereum-based Tokens',
        date: '2024-05-28',
        type: 'Market Release',
        content: 'Coinbase announced the listing of several new ERC-20 tokens, expanding its offerings for Ethereum users. This move is expected to increase liquidity and accessibility for these assets.',
        sentiment: 'positive',
        impactScore: 4,
        tags: ['Exchange', 'Listing', 'ERC-20'],
      },
      {
        id: 6,
        title: 'Ethereum Scaling Solution Arbitrum Announces Nitro Upgrade',
        date: '2024-05-25',
        type: 'Press Release',
        content: 'Arbitrum, a leading Ethereum Layer 2 solution, has announced the successful deployment of its "Nitro" upgrade, promising even faster transaction speeds and lower costs. This is a significant step towards greater scalability.',
        sentiment: 'positive',
        impactScore: 5,
        tags: ['L2', 'Upgrade', 'Arbitrum'],
      },
      {
        id: 7,
        title: 'Security Vulnerability Discovered in Popular Ethereum dApp',
        date: '2024-05-20',
        type: 'Market Release',
        content: 'A critical security vulnerability was identified in a widely used Ethereum decentralized application. Users are advised to withdraw funds immediately. The team is working on a patch.',
        sentiment: 'negative',
        impactScore: 5,
        tags: ['Security', 'Vulnerability', 'dApp'],
      },
      {
        id: 8,
        title: 'Ethereum Community Discusses Future of Sharding',
        date: '2024-05-18',
        type: 'Press Release',
        content: 'Core Ethereum developers and researchers held a public discussion on the long-term roadmap for sharding, exploring various approaches to further enhance network capacity post-Merge.',
        sentiment: 'neutral',
        impactScore: 3,
        tags: ['Sharding', 'Roadmap', 'Development'],
      },
      {
        id: 9,
        title: 'NFT Gaming Project Raises $50M in Seed Round on Ethereum',
        date: '2024-05-12',
        type: 'Market Release',
        content: 'A new play-to-earn NFT gaming project, "EtherQuest," successfully closed a $50 million seed funding round, attracting significant institutional investment. The game is built on Ethereum.',
        sentiment: 'positive',
        impactScore: 4,
        tags: ['NFT Gaming', 'Funding', 'P2E'],
      },
      {
        id: 10,
        title: 'Ethereum Merge Successfully Completed, Transition to PoS',
        date: '2022-09-15', // Historical significant event
        type: 'Press Release',
        content: 'The Ethereum network successfully completed "The Merge," transitioning from Proof-of-Work (PoW) to Proof-of-Stake (PoS). This marks a monumental shift towards a more energy-efficient and scalable blockchain.',
        sentiment: 'positive',
        impactScore: 5,
        tags: ['Merge', 'PoS', 'Network Upgrade'],
      },
      {
        id: 11,
        title: 'Decentralized Social Media Platform Gains Traction on Ethereum',
        date: '2024-04-25',
        type: 'Market Release',
        content: 'Lens Protocol, a decentralized social media graph, has seen a surge in user adoption and content creation, showcasing the potential of Web3 social applications on Ethereum.',
        sentiment: 'positive',
        impactScore: 3,
        tags: ['SocialFi', 'Web3', 'Lens Protocol'],
      },
      {
        id: 12,
        title: 'New Stablecoin Backed by Real-World Assets Launches on Ethereum',
        date: '2024-04-18',
        type: 'Market Release',
        content: 'A new stablecoin, "RealUSD," collateralized by tokenized real estate assets, has launched on Ethereum, aiming to provide a more stable and transparent alternative to traditional stablecoins.',
        sentiment: 'neutral',
        impactScore: 3,
        tags: ['Stablecoin', 'RWA', 'DeFi'],
      },
      {
        id: 13,
        title: 'Ethereum Developers Target Q4 for Shanghai Upgrade',
        date: '2024-03-30',
        type: 'Press Release',
        content: 'Ethereum core developers have tentatively set Q4 as the target for the Shanghai upgrade, which will enable staked ETH withdrawals, a highly anticipated feature post-Merge.',
        sentiment: 'positive',
        impactScore: 4,
        tags: ['Upgrade', 'Staking', 'Roadmap'],
      },
      {
        id: 14,
        title: 'Major Investment Firm Allocates Billions to Ethereum Ecosystem',
        date: '2024-03-10',
        type: 'Market Release',
        content: 'BlackRock announced a significant investment into various projects within the Ethereum ecosystem, signaling growing institutional confidence in the network\'s future.',
        sentiment: 'positive',
        impactScore: 5,
        tags: ['Investment', 'Institutional', 'DeFi'],
      },
      {
        id: 15,
        title: 'Ethereum NFT Volume Dips Amidst Broader Market Downturn',
        date: '2024-02-20',
        type: 'Market Release',
        content: 'NFT trading volume on Ethereum has seen a decline over the past month, mirroring a broader bearish trend in the cryptocurrency market. Analysts remain optimistic for a rebound.',
        sentiment: 'negative',
        impactScore: 2,
        tags: ['NFT', 'Market', 'Downturn'],
      },
    ],
  },
  {
    name: 'Binance',
    logo: 'https://placehold.co/40x40/F3BA2F/FFFFFF?text=BNB',
    releases: [
      {
        id: 1,
        title: 'BNB Chain Announces $1 Billion Ecosystem Growth Fund',
        date: '2024-06-12',
        type: 'Press Release',
        content: 'BNB Chain has launched a new $1 billion fund dedicated to accelerating the development of its ecosystem, focusing on GameFi, DeFi, and Metaverse projects. This initiative aims to attract top talent and innovation.',
        sentiment: 'positive',
        impactScore: 5,
        tags: ['Fund', 'Ecosystem', 'GameFi', 'DeFi'],
      },
      {
        id: 2,
        title: 'PancakeSwap V3 Goes Live with Concentrated Liquidity',
        date: '2024-06-05',
        type: 'Market Release',
        content: 'PancakeSwap, the leading DEX on BNB Chain, has successfully deployed its V3 upgrade, introducing concentrated liquidity and improved capital efficiency for liquidity providers. Trading fees are expected to be more dynamic.',
        sentiment: 'positive',
        impactScore: 4,
        tags: ['DEX', 'Upgrade', 'PancakeSwap'],
      },
      {
        id: 3,
        title: 'Binance Labs Leads Seed Round for New Web3 Gaming Studio',
        date: '2024-05-30',
        type: 'Press Release',
        content: 'Binance Labs, the venture arm of Binance, announced its lead investment in "PixelVerse," a promising new Web3 gaming studio building on BNB Chain. This highlights Binance\'s commitment to the GameFi sector.',
        sentiment: 'positive',
        impactScore: 4,
        tags: ['Investment', 'GameFi', 'Binance Labs'],
      },
      {
        id: 4,
        title: 'BNB Chain Experiences Brief Network Congestion',
        date: '2024-05-20',
        type: 'Market Release',
        content: 'The BNB Chain network experienced temporary congestion due to high transaction volume from a popular NFT game launch. Services quickly normalized, but it prompted discussions on scalability improvements.',
        sentiment: 'negative',
        impactScore: 3,
        tags: ['Network', 'Congestion', 'GameFi'],
      },
      {
        id: 5,
        title: 'Binance Announces Delisting of Several Low-Volume Tokens',
        date: '2024-05-15',
        type: 'Press Release',
        content: 'Binance has announced the delisting of several cryptocurrencies that no longer meet its listing standards, citing low trading volume and liquidity. Users are advised to withdraw affected assets.',
        sentiment: 'negative',
        impactScore: 3,
        tags: ['Delisting', 'Exchange', 'Compliance'],
      },
      {
        id: 6,
        title: 'New Stablecoin Pegged to Euro Launches on BNB Chain',
        date: '2024-05-10',
        type: 'Market Release',
        content: 'A new euro-pegged stablecoin, "EuroBNB," has launched on BNB Chain, aiming to provide a stable and efficient medium of exchange for European users within the ecosystem.',
        sentiment: 'neutral',
        impactScore: 3,
        tags: ['Stablecoin', 'Euro', 'Launch'],
      },
      {
        id: 7,
        title: 'BNB Chain Integrates with Leading Web2 Payment Gateway',
        date: '2024-04-28',
        type: 'Press Release',
        content: 'BNB Chain has partnered with a major traditional payment gateway to facilitate easier fiat-to-crypto on-ramps for users, enhancing accessibility and adoption.',
        sentiment: 'positive',
        impactScore: 4,
        tags: ['Partnership', 'On-Ramp', 'Adoption'],
      },
      {
        id: 8,
        title: 'Record TVL Achieved in BNB Chain DeFi Protocols',
        date: '2024-04-20',
        type: 'Market Release',
        content: 'The Total Value Locked (TVL) in decentralized finance (DeFi) protocols on BNB Chain has reached an all-time high, indicating strong confidence and capital inflow into the ecosystem.',
        sentiment: 'positive',
        impactScore: 5,
        tags: ['DeFi', 'TVL', 'Market'],
      },
      {
        id: 9,
        title: 'Binance Announces New Security Audit Program for dApps',
        date: '2024-04-15',
        type: 'Press Release',
        content: 'To enhance ecosystem security, Binance has rolled out a new program offering free security audits for dApps building on BNB Chain, aiming to reduce vulnerabilities.',
        sentiment: 'positive',
        impactScore: 4,
        tags: ['Security', 'dApp', 'Audit'],
      },
      {
        id: 10,
        title: 'Binance Smart Chain Renamed to BNB Chain',
        date: '2022-02-15', // Historical significant event
        type: 'Press Release',
        content: 'Binance Smart Chain (BSC) has officially rebranded to BNB Chain, reflecting its broader ecosystem beyond just smart contracts, including BNB Beacon Chain and future developments.',
        sentiment: 'neutral',
        impactScore: 3,
        tags: ['Rebrand', 'Ecosystem'],
      },
    ],
  },
  {
    name: 'Solana',
    logo: 'https://placehold.co/40x40/00FF00/000000?text=SOL',
    releases: [
      {
        id: 1,
        title: 'Solana Foundation Launches New Accelerator Program',
        date: '2024-06-18',
        type: 'Press Release',
        content: 'The Solana Foundation has announced the launch of its "Ignite" accelerator program, designed to support early-stage projects building on the Solana blockchain with funding, mentorship, and resources.',
        sentiment: 'positive',
        impactScore: 4,
        tags: ['Foundation', 'Accelerator', 'Development'],
      },
      {
        id: 2,
        title: 'New High-Performance DEX Goes Live on Solana',
        date: '2024-06-14',
        type: 'Market Release',
        content: 'A new decentralized exchange (DEX), "Vortex Protocol," has launched on Solana, leveraging its high throughput to offer ultra-fast and low-cost trading for a wide range of assets.',
        sentiment: 'positive',
        impactScore: 5,
        tags: ['DEX', 'Launch', 'High Performance'],
      },
      {
        id: 3,
        title: 'Solana Network Experiences Minor Outage',
        date: '2024-06-07',
        type: 'Market Release',
        content: 'The Solana network experienced a brief period of reduced performance due to a surge in transaction volume. Engineers quickly resolved the issue, and the network is fully operational.',
        sentiment: 'negative',
        impactScore: 4,
        tags: ['Network', 'Outage', 'Performance'],
      },
      {
        id: 4,
        title: 'Magic Eden Reports Record NFT Trading Volume on Solana',
        date: '2024-06-01',
        type: 'Market Release',
        content: 'Magic Eden, the leading NFT marketplace on Solana, announced a new all-time high in daily trading volume, signaling robust activity in the Solana NFT ecosystem despite broader market conditions.',
        sentiment: 'positive',
        impactScore: 4,
        tags: ['NFT', 'Marketplace', 'Trading Volume'],
      },
      {
        id: 5,
        title: 'Solana Mobile Stack Releases New Developer Tools',
        date: '2024-05-25',
        type: 'Press Release',
        content: 'The Solana Mobile Stack (SMS) has rolled out an updated suite of developer tools, making it easier for builders to create mobile-first decentralized applications on Solana.',
        sentiment: 'positive',
        impactScore: 3,
        tags: ['Mobile', 'Developer Tools', 'SMS'],
      },
      {
        id: 6,
        title: 'Solana Pay Expands Merchant Adoption Globally',
        date: '2024-05-18',
        type: 'Press Release',
        content: 'Solana Pay has announced new partnerships with several international merchants, enabling more businesses to accept SOL and other Solana-based tokens for payments, driving real-world utility.',
        sentiment: 'positive',
        impactScore: 4,
        tags: ['Payments', 'Adoption', 'Partnership'],
      },
      {
        id: 7,
        title: 'New GameFi Project on Solana Attracts Millions in Funding',
        date: '2024-05-10',
        type: 'Market Release',
        content: 'A highly anticipated GameFi project, "Solana Saga," secured significant funding from venture capitalists, aiming to revolutionize blockchain gaming with immersive experiences on Solana.',
        sentiment: 'positive',
        impactScore: 5,
        tags: ['GameFi', 'Funding', 'P2E'],
      },
      {
        id: 8,
        title: 'Solana Validators Discuss Network Decentralization Efforts',
        date: '2024-05-01',
        type: 'Press Release',
        content: 'The Solana validator community held a forum to discuss ongoing efforts and future plans to further decentralize the network, inviting participation from new and existing validators.',
        sentiment: 'neutral',
        impactScore: 3,
        tags: ['Decentralization', 'Validators', 'Network'],
      },
      {
        id: 9,
        title: 'Solana Breakpoint Conference 2023 Dates Announced',
        date: '2024-04-20',
        type: 'Press Release',
        content: 'The Solana Foundation has officially announced the dates and location for its annual flagship conference, Breakpoint 2023, promising major announcements and community gatherings.',
        sentiment: 'positive',
        impactScore: 3,
        tags: ['Conference', 'Community'],
      },
      {
        id: 10,
        title: 'Solana Network Outage Post-FTX Collapse Analysis',
        date: '2022-11-15', // Historical significant event
        type: 'Press Release',
        content: 'Following the FTX collapse, the Solana network experienced a period of instability. A detailed post-mortem analysis was released, outlining the causes and preventative measures implemented.',
        sentiment: 'negative',
        impactScore: 5,
        tags: ['FTX', 'Network', 'Post-Mortem'],
      },
    ],
  },
];

export const getPressReleaseChainData = (chainName) => {
  return pressReleaseChainsData.find(chain => chain.name.toLowerCase() === chainName.toLowerCase());
};
